(function(j,a){function n(c){(new Image).src=[c,"r="+Math.random()].join("&")}function s(c){K.geocode({location:c.latLng||k},function(a,d){var h,f;if(d===soso.maps.GeocoderStatus.OK){h=a.addressComponents;f=h.province||"";if(f!==""&&f===h.city&&"\u5317\u4eac\u5e02\u4e0a\u6d77\u5e02\u5929\u6d25\u5e02\u91cd\u5e86\u5e02\u9999\u6e2f\u7279\u522b\u884c\u653f\u533a\u6fb3\u95e8\u7279\u522b\u884c\u653f\u533a\u53f0\u6e7e\u7701".indexOf(f)===-1)h.city=h.district;a.ec=0}else if(a={ec:10,status:d},d!==d.NO_RESULTS)a.ec=
11;c.callback(a)})}function U(a){var b=new soso.maps.LatLngCircles(k,1200);F.search({keyword:a.keyword,region:b,pageCapacity:a.pageSize,pageIndex:a.pageIndex},function(b,h){if(h==soso.maps.SearchStatus.OK)b.ec=0;else if(b={ec:10,status:h},h!==soso.maps.SearchStatus.NO_RESULTS){b.ec=11;try{n("http://jsreport.qq.com/cgi-bin/report?id=167&rs=0-0-362771")}catch(f){}}a.callback(b)})}function V(){a.http.loadScript("http://1.url.cn/qun/profile_webkit/js/10/city.js",function(){L()})}function L(){j.cityControl&&
M&&(cityControl.init(),s({callback:function(a){if(a.ec===0)a=a.addressComponents,j.cityControl&&cityControl.updateTitle(a.province,a.city)}}))}function N(a){var b,d;if(a.ec===0){b=a.addressComponents;[b.district,b.town,b.village].join("");if(d=b.city?a.address.split(b.city)[1]:a.address)p.addr=a,p.addr.latLng=a.location,p.combName=d;j.cityControl&&cityControl.updateTitle(b.province,b.city)}o.setContent({mode:0,txt:"\u5f53\u524d\u4f4d\u7f6e\uff1a"+(d||"\u6682\u65e0\u8be6\u7ec6\u4f4d\u7f6e\u6570\u636e")});
o.show()}function z(a){parent.MapManage&&parent.MapManage.close(a)}function G(a){var b=document.createElement("span"),d={};d.width=b.offsetWidth;d.height=b.offsetWidth;b.style.visibility="hidden";document.body.appendChild(b);typeof b.textContent!="undefined"?b.textContent=a:b.innerText=a;d.width=b.offsetWidth-d.width;d.height=b.offsetHeight-d.height;b.parentNode.removeChild(b);return d}function W(){var a=i.fromLatLngToContainerPixel(m.getPosition());a.x>255&&i.moveBy(new soso.maps.Size(-parseInt(a.x-
120),0))}var t=a.bom.getHash("edit")=="1"?true:false,A=parseFloat(a.bom.getHash("lng")),B=parseFloat(a.bom.getHash("lat")),q=a.bom.getHash("name"),O=q,P=a.css.removeClass,Q=a.css.addClass,x=a.dom.queryClass,p={addr:null,clear:function(){p.addr=null}},H={},M,k,R,K,i,m,o,F,y;a.badjs.init(211,215883,215884);var S={hdMapDragStart:function(){u.go2();!O&&!C.has_pos()&&(C.hide(),o.hide(),m.setVisible(false))},hdMapClick:function(c){c=c.latLng;k.equals(c)||(k=c,p.clear(),s({callback:function(a){N(a);m.getVisible()||
(m.setVisible(true),o.show())}}),m.setPosition(k),W(),u.go3(),O=null,a.oop.notifyObservers(H,"changeLatLng",{latLng:k}))},hdZoomChanged:function(){o.traceMarker()},hdLatLngStart:function(){o.hide()},hdMarkerDragEnd:function(){k=m.getPosition();p.clear();s({callback:N});S.hdDragging();y=setTimeout(function(){y=null;a.oop.notifyObservers(H,"changeLatLng",{latLng:k})},1E3)},hdDragging:function(){y&&(clearTimeout(y),y=null);C.hide()},hdClose:function(){z()}},C=function(){function c(){v=a("rs_pnl");q=
a("catelog");dom={ly:a("ly"),sh:a("sh"),ggfw:a("ggfw"),ms:a("ms")};a.e.add(q,"click",T);a.e.add(x("cancel","a",v),"click",b);a.e.add(x("save","a",v),"click",f);j=true;a.array.forEach(["ly","sh","ggfw","ms"],function(b){var c={};c.dom=a(b);c.listView=new C(c.dom);w[b]=c});r();T.call(q,{target:x(y,"a",v)})}function b(){o.hide();m.setVisible(false);u.reset();g()}function d(){D||(D=true,P(x("save","a",v),"disable"))}function h(){D&&(D=false,Q(x("save","a",v),"disable"))}function f(){var a,b,c,d,e;if(D)if(a=
w[i()].listView.getVal())if(a.combName){b=a.addr;c=b.addressComponents||{};e={name:a.combName,lat:b.latLng.lat,lng:b.latLng.lng,city:c.city,province:c.province};if(!e.province&&(e.province=(b.address||"").replace("\u4e2d\u56fd",""),e.province.indexOf("\u53f0\u6e7e\u7701")>-1))e.province="\u53f0\u6e7e\u7701";g();z(e)}else e={name:a.name,lat:a.latLng.lat,lng:a.latLng.lng},b=(p.addr||{}).addressComponents||{},b.province?(e.province=b.province,e.city=b.city,g(),z(e)):s({latLng:a.latLng,callback:function(a){if(a.ec===
0)b=a.addressComponents||{},(d=b.province)||(d=(b.address||"").replace("\u4e2d\u56fd","")),e.province=d,e.city=b.city||"",g(),z(e)}});else z(a)}function g(){if(n)n=false,v.style.display="none"}function r(){n=true;v.style.display="block";a.oop.notifyObservers(window,"resize")}function T(a){a=a.target;if(!(a===this||a===E)){h();if(E)P(E,t),w[i()].dom.style.display="none",w[i()].listView.blur();E=a;Q(a,t);w[i()].dom.style.display="block";w[i()].listView.focus()}}function i(){return E&&E.getAttribute("data-idx")||
"ly"}var j,n,w={},v,q,E,t="highlight",y=a.bom.getHash("category")||"ly",D=false,A=function(){function b(e){var X=this.cursorSet,f=this.cache,h=k,r=0,I=0,g=0,i=0;a.array.forEach(this.subCategoryList,function(a,b){(function(b){b.isFinished()||(r+=1,I+=1,U({keyword:a,callback:function(a){var d=a.ec;h.equals(k)&&(r-=1,d===0?(a=c(a),b.record(a.totalNum,a.list.length),f.add(a.list)):a.ec===10?(b.record(0,0),g+=1):i+=1,r===0&&(g===I?e({ec:10,ls:[]}):i===I?e({ec:11}):(f.sort(function(a,b){var e=a.latLng,
c=b.latLng;return Math.abs(e.lat-h.lat)+Math.abs(e.lng-h.lng)>Math.abs(c.lat-h.lat)+Math.abs(c.lng-h.lng)}),f.unique(function(a,b){return a.name===b.name}),a=f.get(),e({ec:0,ls:a}))))},pageSize:d.pageSize,pageIndex:b.getNextPageIndex()}))})(X[b])});r===0&&e({ec:10,ls:[]})}function c(a){var b={list:[],totalNum:0};if(!a)return b;b.totalNum=a.totalNum;var a=a.pois,e,d;for(d=0,l=a.length;d<l;d++)e=a[d],b.list.push({name:e.name,address:e.address,city:e.city,latLng:e.latLng});return b}var d={ly:["\u623f\u4ea7\u5c0f\u533a"],
sh:["\u7efc\u5408\u5546\u573a","\u5a31\u4e50\u4f11\u95f2","\u8fd0\u52a8\u5065\u8eab","\u65c5\u6e38\u666f\u70b9"],ggfw:["\u7efc\u5408\u533b\u9662","\u6587\u5316\u573a\u9986","\u6559\u80b2\u5b66\u6821"],ms:["\u7f8e\u98df"],pageSize:10},h=function(){var a=[];return{add:function(b){[].push.apply(a,b)},clear:function(){a=[]},get:function(b){b||(b=10);return a.splice(0,Math.min(b,a.length))},size:function(){return a.length},sort:function(b){a=a.sort(b)},unique:function(b){var e=[],c={},d,f,h;for(f=0,h=
a.length;f<h;f++)d=a[f],b(d,c)||(c=d,e.push(d));a=e}}},e=function(){var a=-1,b=0;return{isFinished:function(){return-1!==a&&a<=b},record:function(e,d){b+=d;a=e},reset:function(){b=0;a=-1},getNextPageIndex:function(){return parseInt(b/d.pageSize)}}},f=function(b){var c=this;c.category=b.category;c.subCategoryList=d[b.category];c.cache=new h;c.cursorSet={};a.array.forEach(c.subCategoryList,function(a,b){c.cursorSet[b]=new e})};f.prototype.loadNext=function(a){this.cache.size()>0?a({ec:0,ls:this.cache.get(d.pageSize)}):
b.call(this,a)};f.prototype.reset=function(){var b=this;a.array.forEach(b.subCategoryList,function(a,e){b.cursorSet[e].reset()});b.cache.clear()};return f}(),B=function(){function b(a){var c=this.self,a=a.target;if(a!==this){for(;!a.getAttribute("data-click");)a=a.parentNode;c=c.selectMark;c.parentNode&&c.parentNode.removeChild(c);a.appendChild(c);c=a["data-meta"];m.setPosition(c.latLng);o.setContent({mode:2,name:c.name,addr:c.address});d()}}function c(d,f){this.dom=a.dom.getNode("ul");this.dom.self=
this;this.arrNames=[];this.selectMark=a.dom.getNode("strong",{"class":"comm-bg"});this.append(f);d.appendChild(this.dom);a.e.add(this.dom,"click",b)}c.prototype={reset:function(a){this.dom.innerHTML="";this.arrNames=[];this.append(a)},append:function(b){var c,e,d,f,h=this.dom,r=this.arrNames;if(b){f=document.createDocumentFragment();for(e=0,l=b.length;e<l;e++){c=b[e];d=a.dom.getNode("li");d.setAttribute("data-click","Y");var g=c.name;if(a.array.indexOf(r,g)===-1)r.push(g),d.innerHTML='<a href="##" hidefocus><label>'+
a.str.encodeHtml(g)+"</label><span>"+a.str.encodeHtml(c.address)+"</span></a>",d["data-meta"]=c,f.appendChild(d)}h.appendChild(f)}},getVal:function(){var a=null,b=this.selectMark.parentNode;b&&(a=b["data-meta"]);return a},selected:function(){return!!this.selectMark.parentNode}};return c}(),C=function(){function b(){var a=this,c=a.self;clearTimeout(a.scorllId);if(!c.scrolling)a.scorllId=setTimeout(function(){if(a.scrollHeight-(a.scrollTop+a.clientHeight)<=5)c.scrolling=true,c.dataProvider.loadNext(function(a){f.call(c,
a)})},500)}function c(d,f){this.self=d;d.self=this;this.scorllId=null;this.hasFocus=this.scrolling=this.hasInitList=this.usedCenterData=false;this.cover=x("cover","div",d);this.dataProvider=new A({category:d.id});this.listCore=new B(d,f);a.e.add(d,"scroll",b)}function f(a){this.scrolling=false;!this.hasInitList&&a.ec!==0?a.ec===10?(this.hasInitList=true,p.addr?(this.usedCenterData=true,this.cover.innerHTML="\u5f53\u524d\u4f4d\u7f6e\uff1a"+p.combName+"<br>\u672a\u627e\u5230\u9644\u8fd1\u7684\u5730\u70b9\uff0c<br>\u60a8\u53ef\u4ee5\u4fdd\u5b58\u5f53\u524d\u4f4d\u7f6e\u6216\u91cd\u65b0\u5b9a\u4f4d\u3002",
this.hasFocus&&d()):this.cover.innerHTML="\u5f53\u524d\u4f4d\u7f6e\u9644\u8fd1\u6ca1\u6709\u627e\u5230\u76f8\u5173\u5730\u70b9\uff0c<br>\u8bf7\u60a8\u91cd\u65b0\u5b9a\u4f4d\u3002"):this.cover.innerHTML="\u670d\u52a1\u5668\u7e41\u5fd9\uff0c\u8bf7\u7a0d\u540e\u91cd\u8bd5\u3002":(this.hasInitList=true,this.listCore.append(a.ls),this.cover.style.display="none")}function h(){var a=this;a.cover.style.display="block";a.cover.innerHTML="\u8bf7\u7a0d\u5019\uff0c\u6b63\u5728\u62c9\u53d6\u9644\u8fd1\u7684\u5730\u70b9";
a.dataProvider.loadNext(function(b){f.call(a,b)})}c.prototype={reset:function(){this.listCore.reset();this.hasInitList=this.scrolling=this.usedCenterData=false;this.dataProvider.reset();clearTimeout(this.scorllId);this.hasFocus&&h.call(this)},focus:function(){this.hasFocus=true;this.hasInitList||h.call(this);(this.listCore.selected()||this.usedCenterData)&&d()},blur:function(){this.hasFocus=false},getVal:function(){return this.usedCenterData?p:this.listCore.getVal()}};return c}();a.oop.addObserver(H,
"changeLatLng",function(){if(j){for(var a in w)w[a].listView.reset();h()}else c();n||r()});return{hide:g,has_pos:function(){return D}}}(),u=function(){var c=a("step");clsOne="step";clsTwo="step second";clsThird="step third";whichStep=1;return{reset:function(){if(whichStep!==1)c.className=clsOne,whichStep=1},go2:function(){if(whichStep!==2)c.className=clsTwo,whichStep=2},go3:function(){if(whichStep!==3)c.className=clsThird,whichStep=3},show:function(){a.css.show(c)}}}(),Y=function(){function c(c){var g,
i;h=c.mode;i="58px";c.mode===0||c.mode===1?(g=G(c.txt).width+24,g=Math.max(g-51,30),g=b.replace("$outerWidth$",g+51+"px").replace("$midWidth$",g+"px").replace("htmlText",c.txt),i="38px"):c.mode===2&&(g=Math.max(G(c.name).width,G(c.addr).width)+24,g=Math.max(g-51,30),g=b.replace("label","label multi").replace("$outerWidth$",g+51+"px").replace("$midWidth$",g+"px").replace("htmlText",a.str.encodeHtml(c.name)+'<p class="addr">'+a.str.encodeHtml(c.addr)+"</p>"));f.setStyle({height:i});setTimeout(function(){x("text",
"div",d).style.zoom=1},0);return g}var b='<div class="label" style="width: $outerWidth$">        <div class="left-arrow comm-bg"></div>        <div class="mid" style="width: $midWidth$"></div>        <div class="right  comm-bg"></div>        <div class="text">htmlText</div>        </div>',d=a.dom.getNode("div"),h=0,f=new soso.maps.Label({position:k,map:i,content:d,visible:false,style:{fontSize:"12px",border:"none"}});setTimeout(function(){try{d.parentNode.style.filter=""}catch(a){}},0);var g={setContent:function(a){d.innerHTML=
c(a);g.traceMarker()},reset:function(){d.innerHTML=c({mode:0,txt:"\u62d6\u52a8\u6307\u9488\uff0c\u627e\u5230\u7fa4\u6240\u5728\u4f4d\u7f6e"});g.traceMarker()},setPosition:function(a){f.setPosition(a)},show:function(){f.setVisible(true)},hide:function(){f.setVisible(false)},traceMarker:function(){var a=i.fromLatLngToContainerPixel(m.getPosition()),a=new soso.maps.Point(a.getX()-49,a.getY()-(h===0?57:67));this.setPosition(i.fromContainerPixelToLngLat(a))}};g.reset();return g};j.changeCity=function(a){var b=
a.latLng,a=a.zoom;latLng=new soso.maps.LatLng(b.lat,b.lng);a==i.getZoomLevel()?i.moveTo(latLng):i.zoomTo(a,latLng);k=latLng;m.setPosition(k);m.setVisible(false);o.hide();u.reset();C.hide()};var J={randIn:function(a){return parseInt(Math.random()*(a||100))},fuzzy:function(a){function b(){return(J.randIn()>50?1:-1)*J.randIn(8E3)/1E6}return{lat:a.lat+b(),lng:a.lng+b()}}};j.onload=function(){if(j.navigator.userAgent.toUpperCase().indexOf("NT 6.")>-1)document.body.style.fontFamily='"\u5fae\u8f6f\u96c5\u9ed1","\u5b8b\u4f53",Tahoma,Verdana,Arial,Helvetica,sans-serif';
var c=a("wrap");t||a.css.addClass(c,"readonly");a.e.add(a("close"),"click",function(){z()});if(j.soso){k=new soso.maps.LatLng(39.916527,116.397128);i=new soso.maps.Map(document.getElementById("container"),{center:k,zoomLevel:13});F=new soso.maps.SearchService;R=new soso.maps.Geolocation;K=new soso.maps.Geocoder;var b=function(a,b){i.setCenter(a);new soso.maps.NavigationControl({align:soso.maps.ALIGN.TOP_LEFT,margin:new soso.maps.Size(5,t?35:6),map:i,style:soso.maps.NavigationControlStyle.LARGE});
m=new soso.maps.Marker({position:k,map:i,draggable:t,visible:false});o=new Y;M=true;L();b&&(m.setPosition(a),m.setVisible(true),o.setContent({mode:0,txt:b}),o.show());var c=S;t&&(soso.maps.Event.addListener(m,"dragstart",c.hdLatLngStart),soso.maps.Event.addListener(m,"dragend",c.hdMarkerDragEnd),soso.maps.Event.addListener(m,"dragging",c.hdDragging),soso.maps.Event.addListener(i,"click",c.hdMapClick),soso.maps.Event.addListener(i,"dragstart",c.hdMapDragStart));soso.maps.Event.addListener(i,"zoomlevel_changed",
c.hdZoomChanged)},d=function(){a.http.post("/cgi-bin/qun_info/get_city",{bkn:_DJB(a.cookie.get("skey"))},function(a){var c=a.latitude,a=a.longitude;c&&a?(c=J.fuzzy({lat:c/1E6,lng:a/1E6}),c=new soso.maps.LatLng(c.lat,c.lng),b(c)):R.position({},function(a,c){if(c==soso.maps.GeolocationStatus.OK)k=a.latLng,b(k);else try{n("http://jsreport.qq.com/cgi-bin/report?id=167&rs=0-0-362772")}catch(d){}})});u.reset()};q&&B&&A&&B>=-90&&B<=90&&A>=-180&&A<=180?(k=new soso.maps.LatLng(B,A),b(k,q),u.go2()):q?F.search({keyword:q},
function(a,c){var g=a.pois;g.length!=0?(b(g[0].latLng,q),u.go3()):d();try{c==soso.maps.SearchStatus.OK&&c!==soso.maps.SearchStatus.NO_RESULTS&&n("http://jsreport.qq.com/cgi-bin/report?id=167&rs=0-0-362771")}catch(i){}}):d();t&&(V(),u.show())}else container.innerHTML='<p class="err-info">\u5bf9\u4e0d\u8d77\uff0c\u5730\u56fe\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5\uff01</p>',a.badjs("\u5730\u56fe\uff1amap.js\u52a0\u8f7d\u5931\u8d25",location.href,0,374961,4)}})(this,$);
var _DJB=function(j){if(!j)return"";for(var a=5381,n=0,s=j.length;n<s;++n)a+=(a<<5)+j.charAt(n).charCodeAt();return a&2147483647};(function(){var j,a=$("inner"),n=$("loc-list"),s=function(){clearTimeout(j);j=setTimeout(function(){var j;if(j=a.parentNode.clientHeight)a.style.height=j-30+"px";if(j=n.parentNode.clientHeight)n.style.height=j-68+"px"},100)};$.e.add(window,"resize",s);$.oop.addObserver(window,"resize",s);$.oop.notifyObservers(window,"resize")})();
