/*
 RequireJS text 2.0.10 Copyright (c) 2010-2012, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/requirejs/text for details
*/
define(["module"],function(n){var f,o,i,j,p,q=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],r=/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,s=/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im,k=typeof location!=="undefined"&&location.href,t=k&&location.protocol&&location.protocol.replace(/\:/,""),u=k&&location.hostname,v=k&&(location.port||void 0),m={},g=n.config&&n.config()||{};f={version:"2.0.10",strip:function(b){if(b){var b=b.replace(r,""),e=b.match(s);e&&(b=e[1])}else b="";return b},
jsEscape:function(b){return b.replace(/(['\\])/g,"\\$1").replace(/[\f]/g,"\\f").replace(/[\b]/g,"\\b").replace(/[\n]/g,"\\n").replace(/[\t]/g,"\\t").replace(/[\r]/g,"\\r").replace(/[\u2028]/g,"\\u2028").replace(/[\u2029]/g,"\\u2029")},createXhr:g.createXhr||function(){var b,e,d;if(typeof XMLHttpRequest!=="undefined")return new XMLHttpRequest;else if(typeof ActiveXObject!=="undefined")for(e=0;e<3;e+=1){d=q[e];try{b=new ActiveXObject(d)}catch(c){}if(b){q=[d];break}}return b},parseName:function(b){var e,
d,c=false,a=b.indexOf(".");e=b.indexOf("./")===0||b.indexOf("../")===0;a!==-1&&(!e||a>1)?(e=b.substring(0,a),d=b.substring(a+1,b.length)):e=b;b=d||e;a=b.indexOf("!");a!==-1&&(c=b.substring(a+1)==="strip",b=b.substring(0,a),d?d=b:e=b);return{moduleName:e,ext:d,strip:c}},xdRegExp:/^((\w+)\:)?\/\/([^\/\\]+)/,useXhr:function(b,e,d,c){var a,h;a=f.xdRegExp.exec(b);if(!a)return true;b=a[2];a=a[3];a=a.split(":");h=a[1];a=a[0];return(!b||b===e)&&(!a||a.toLowerCase()===d.toLowerCase())&&(!h&&!a||h===c)},finishLoad:function(b,
e,d,c){d=e?f.strip(d):d;g.isBuild&&(m[b]=d);c(d)},load:function(b,e,d,c){if(c.isBuild&&!c.inlineText)d();else{g.isBuild=c.isBuild;var a=f.parseName(b),c=a.moduleName+(a.ext?"."+a.ext:""),h=e.toUrl(c),l=g.useXhr||f.useXhr;h.indexOf("empty:")===0?d():!k||l(h,t,u,v)?f.get(h,function(c){f.finishLoad(b,a.strip,c,d)},function(a){d.error&&d.error(a)}):e([c],function(b){f.finishLoad(a.moduleName+"."+a.ext,a.strip,b,d)})}},write:function(b,e,d){if(m.hasOwnProperty(e)){var c=f.jsEscape(m[e]);d.asModule(b+"!"+
e,"define(function () { return '"+c+"';});\n")}},writeFile:function(b,e,d,c,a){var e=f.parseName(e),h=e.ext?"."+e.ext:"",l=e.moduleName+h,g=d.toUrl(e.moduleName+h)+".js";f.load(l,d,function(){var d=function(a){return c(g,a)};d.asModule=function(a,b){return c.asModule(a,g,b)};f.write(b,l,d,a)},a)}};if(g.env==="node"||!g.env&&typeof process!=="undefined"&&process.versions&&process.versions.node&&!process.versions["node-webkit"])o=require.nodeRequire("fs"),f.get=function(b,e,d){try{var c=o.readFileSync(b,
"utf8");c.indexOf("\ufeff")===0&&(c=c.substring(1));e(c)}catch(a){d(a)}};else if(g.env==="xhr"||!g.env&&f.createXhr())f.get=function(b,e,d,c){var a=f.createXhr(),h;a.open("GET",b,true);if(c)for(h in c)c.hasOwnProperty(h)&&a.setRequestHeader(h.toLowerCase(),c[h]);if(g.onXhr)g.onXhr(a,b);a.onreadystatechange=function(){var c;if(a.readyState===4&&(c=a.status,c>399&&c<600?(c=Error(b+" HTTP status: "+c),c.xhr=a,d(c)):e(a.responseText),g.onXhrComplete))g.onXhrComplete(a,b)};a.send(null)};else if(g.env===
"rhino"||!g.env&&typeof Packages!=="undefined"&&typeof java!=="undefined")f.get=function(b,e){var d,c,a=new java.io.File(b),h=java.lang.System.getProperty("line.separator"),a=new java.io.BufferedReader(new java.io.InputStreamReader(new java.io.FileInputStream(a),"utf-8")),f="";try{d=new java.lang.StringBuffer;(c=a.readLine())&&c.length()&&c.charAt(0)===65279&&(c=c.substring(1));for(c!==null&&d.append(c);(c=a.readLine())!==null;)d.append(h),d.append(c);f=String(d.toString())}finally{a.close()}e(f)};
else if(g.env==="xpconnect"||!g.env&&typeof Components!=="undefined"&&Components.classes&&Components.interfaces)i=Components.classes,j=Components.interfaces,Components.utils["import"]("resource://gre/modules/FileUtils.jsm"),p="@mozilla.org/windows-registry-key;1"in i,f.get=function(b,e){var d,c,a,f={};p&&(b=b.replace(/\//g,"\\"));a=new FileUtils.File(b);try{d=i["@mozilla.org/network/file-input-stream;1"].createInstance(j.nsIFileInputStream),d.init(a,1,0,false),c=i["@mozilla.org/intl/converter-input-stream;1"].createInstance(j.nsIConverterInputStream),
c.init(d,"utf-8",d.available(),j.nsIConverterInputStream.DEFAULT_REPLACEMENT_CHARACTER),c.readString(d.available(),f),c.close(),d.close(),e(f.value)}catch(g){throw Error((a&&a.path||"")+": "+g);}};return f});
