define(["jquery"],function(j){(function(d){function l(a,b,d){var e=a.data("ddslick");if(e){var h=a.find(".dd-selected"),f=h.siblings(".dd-selected-value");a.find(".dd-options");h.siblings(".dd-pointer");var c=a.find(".dd-option").eq(b),j=c.closest("li"),k=e.settings,i=e.settings.data[b];a.find(".dd-option").removeClass("dd-option-selected");c.addClass("dd-option-selected");e.selectedIndex=b;e.selectedItem=j;e.selectedData=i;k.showSelectedHTML?h.html((i.imageSrc?'<img class="dd-selected-image'+(k.imagePosition==
"right"?" dd-image-right":"")+'" src="'+i.imageSrc+'" />':"")+(i.text?'<label class="dd-selected-text">'+i.text+"</label>":"")+(i.description?'<small class="dd-selected-description dd-desc'+(k.truncateDescription?" dd-selected-description-truncated":"")+'" >'+i.description+"</small>":"")):h.html(i.text);f.val(i.value);e.original.val(i.value);a.data("ddslick",e);m(a);b=a.find(".dd-select").css("height");h=a.find(".dd-selected-description");f=a.find(".dd-selected-image");h.length<=0&&f.length>0&&a.find(".dd-selected-text").css("lineHeight",
b);typeof k.onSelected=="function"&&d!==true&&k.onSelected.call(this,e)}}function j(a){var b=a.find(".dd-select"),g=b.siblings(".dd-options"),e=b.find(".dd-pointer"),h=g.is(":visible"),f=a.data("ddslick");d(".dd-click-off-close").not(g).slideUp(50);d(".dd-select").not(b).removeClass("dd-select-open");d(".dd-pointer").removeClass("dd-pointer-up");if(h)g.fadeOut("fast",function(){d(this).css("top","auto")}),e.removeClass("dd-pointer-up"),b.removeClass("dd-select-open");else if(n=a,g.css("max-height",
"0px").fadeIn("fast"),e.addClass("dd-pointer-up"),b.addClass("dd-select-open"),f.settings.constrain){var c=g.find("li"),c=Math.min(c.length*26,208);g.height();b=g.offset();e=d(f.settings.constrain);f=e.height();e=e.offset();f=e.top+f;b.top+c<=f?g.css({"max-height":c+"px",top:"auto"}):b.top+104<=f?g.css({"max-height":f-b.top-5+"px",top:"auto"}):(c=Math.min(b.top-e.top-26,c),g.css("top",-c+"px").css("max-height",c+"px"))}else g.css({"max-height":c+"px",top:"auto"});o(a)}function m(a){a.find(".dd-select").removeClass("dd-select-open");
a.find(".dd-options").slideUp(50);a.find(".dd-pointer").removeClass("dd-pointer-up").removeClass("dd-pointer-up")}function o(a){a.find(".dd-option").each(function(){var b=d(this),c=b.css("height"),e=b.find(".dd-option-description"),h=a.find(".dd-option-image");e.length<=0&&h.length>0&&b.find(".dd-option-text").css("lineHeight",c)})}d.fn.ddslick=function(a){if(c[a])return c[a].apply(this,Array.prototype.slice.call(arguments,1));else if(typeof a==="object"||!a)return c.init.apply(this,arguments);else d.error("Method "+
a+" does not exists.")};var c={},p={data:[],keepJSONItemsOnTop:false,width:260,height:null,background:"transparent",selectText:"",defaultSelectedIndex:null,truncateDescription:true,imagePosition:"left",showSelectedHTML:true,clickOffToClose:true,constrain:null,onSelected:function(){},onClick:function(){}},n=null;d("#css-ddslick").length<=0&&d('<style id="css-ddslick" type="text/css"></style>').appendTo("head");d("body").on("click",function(a){d(a.target).closest(".dd-container").length||n&&m(n)});
c.init=function(a){a=d.extend({},p,a);return this.each(function(){var b=d(this);b.data("ddslick");var c=[];b.find("option").each(function(){var a=d(this),b=a.data();c.push({text:d.trim(a.text()),value:a.val(),selected:a.is(":selected"),description:b.description,imageSrc:b.imagesrc})});a.keepJSONItemsOnTop?d.merge(a.data,c):a.data=d.merge(c,a.data);d('<div id="'+b.attr("id")+'"></div>');b.addClass("dd-container dd-select-common dd-select-enable").empty().append('<div class="dd-select"><input class="dd-selected-value" type="hidden" /><a class="dd-selected"></a><span class="dd-pointer dd-pointer-down"></span></div>').append('<ul class="dd-options"></ul>');
var c=b.find(".dd-select"),e=b.find(".dd-options");e.css({width:a.width-2,padding:1});c.css({width:a.width,background:a.background});b.css({width:a.width});a.height!=null&&e.css({height:a.height,overflow:"auto"});d.each(a.data,function(b,c){if(c.selected)a.defaultSelectedIndex=b;e.append('<li><a class="dd-option">'+(c.value?' <input class="dd-option-value" type="hidden" value="'+c.value+'" />':"")+(c.imageSrc?' <img class="dd-option-image'+(a.imagePosition=="right"?" dd-image-right":"")+'" src="'+
c.imageSrc+'" />':"")+(c.text?' <label class="dd-option-text">'+c.text+"</label>":"")+(c.description?' <small class="dd-option-description dd-desc">'+c.description+"</small>":"")+"</a></li>")});b.data("ddslick",{settings:a,original:b,selectedIndex:-1,selectedItem:null,selectedData:null});a.selectText.length>0&&a.defaultSelectedIndex==null?b.find(".dd-selected").html(a.selectText):l(b,a.defaultSelectedIndex!=null&&a.defaultSelectedIndex>=0&&a.defaultSelectedIndex<a.data.length?a.defaultSelectedIndex:
0);b.find(".dd-select").off("click.ddslick").on("click.ddslick",function(){if(a.onClick)a.onClick();b.hasClass("dd-select-disable")||j(b)});b.find(".dd-option").off("click.ddslick").on("click.ddslick",function(){l(b,d(this).closest("li").index())});a.clickOffToClose&&e.addClass("dd-click-off-close")})};c.select=function(a){return this.each(function(){typeof a.index!="undefined"&&l(d(this),a.index,a.quiet)})};c.value=function(){return d(this).data("ddslick").selectedData.value};c.selectedIndex=function(){return d(this).data("ddslick").selectedIndex};
c.disable=function(){d(this).removeClass("dd-select-enable").addClass("dd-select-disable")};c.enable=function(){d(this).removeClass("dd-select-disable").addClass("dd-select-enable")};c.open=function(){return this.each(function(){var a=d(this);a.data("ddslick")&&j(a)})};c.close=function(){return this.each(function(){var a=d(this);a.data("ddslick")&&m(a)})};c.destroy=function(){return this.each(function(){var a=d(this),b=a.data("ddslick");if(b)b=b.original,a.removeData("ddslick").unbind(".ddslick").replaceWith(b)})}})(j);
return j});
