(function(a,j){typeof define==="function"&&define.amd?define("../../../common/js/reportPatchSimple,./db_app,../common/util,../common/client,../common/hintState,commonapi".split(","),j):a.Tags=j(a.$,a.DB,a.Util,a.Client,a.HintState,a.CommonApi)})(this,function(a,j,r,g,D,A){var w,m,s,t,u,x,y,n,B;function z(){a("ui-tags").children.length<=0?a.css.addClass(a("marked-tags"),"qun-tags-empty"):a.css.removeClass(a("marked-tags"),"qun-tags-empty")}function E(){function c(c,d){f||(a.str.byteLen(c,3)>w?g.showTips("\u7fa4\u6807\u7b7e\u6700\u591a"+
w/3+"\u4e2a\u6c49\u5b57"):i.qunTags[c]===1?g.showTips("\u7fa4\u5df2\u7ecf\u88ab\u8d34\u4e0a\u4e86\u8be5\u7fa4\u6807\u7b7e"):g.callClientAPI("IsSelfOnline")?(f=true,j.set_group_more_info({param:{gc:m,tag:c},succ:function(e){n++;f=false;var k=a.dom.getNode("a",{"class":"tag-wrap can-delete js-tag",tid:e.sTid,uin:i.uin,title:(i.nick||"\u81ea\u5df1")+"\uff08"+i.uin+"\uff09\u5f20\u8d34",href:"#",hideFocus:"true","aria-label":"del\u952e\u5220\u9664"}),q=a.dom.getNode("span",{"class":"tag"});q.innerHTML=
a.str.encodeHtml(c);var F=a.dom.getNode("em",{title:"\u5220\u9664"});k.appendChild(q);k.appendChild(F);b.appendChild(k);a.array.forEach(b.children,function(a){a.setAttribute("tabindex","-1")});k.setAttribute("tabindex","2");i.qunTags[c]=1;d?l("TAGS_ADD_HOT_TAG_SUCC"):(a("ui-ipt-addTag").value="",l("TAGS_ADD_USR_TAG_SUCC"));k=(a.dom.queryClassAll("js-tag","a",a("ui-tags"))||[]).length;a.oop.notifyObservers(o,"onTagChange",{action:"add",tagText:c,tagID:e.sTid,total:k});z();var g=document.activeElement;
g.blur();setTimeout(function(){g.focus()},100)},err:function(a){f=false;var c=1;switch(a.ec){case 14:a="\u7fa4\u6807\u7b7e\u4e2d\u5305\u542b\u654f\u611f\u8bcd";c=2;l("TAGS_SENSITIVE");break;case 15:a="\u7528\u623724\u5c0f\u65f6\u5185\u53ea\u80fd\u8d345\u6b21";l("TAGS_FREQ_24H");break;case 16:a="\u7fa4\u6807\u7b7e\u6570\u76ee\u5df2\u8fbe\u5230\u4e0a\u9650";break;case 9999:a="\u64cd\u4f5c\u8d85\u65f6\u4e86";break;default:a="\u8d34\u7fa4\u6807\u7b7e\u51fa\u9519\u4e86"}g.showTips(a,c)}})):g.showTips("\u60a8\u5df2\u7ecf\u5904\u4e8e\u79bb\u7ebf\u72b6\u6001\uff0c\u8bf7\u4e0a\u7ebf\u540e\u518d\u6b21\u5c1d\u8bd5"))}
var b=a("ui-tags"),d=s;d.length>0&&a.insertTags(b,d,t);z();b.firstElementChild&&b.firstElementChild.setAttribute("tabindex","2");var f=false;a.e.add(a("ui-addTag"),"click",x=function(){if(n>20)A.alert(1,"\u6e29\u99a8\u63d0\u793a","\u7fa4\u6807\u7b7e\u6570\u76ee\u5df2\u8d85\u8fc720\u4e2a\u4e0a\u9650\uff0c\u5efa\u8bae\u60a8\u7cbe\u7b80\u7fa4\u6807\u7b7e\uff0c\u65b9\u4fbf\u5927\u5bb6\u4e86\u89e3\u60a8\u7684\u7fa4");else if(n==20)A.alert(1,"\u6e29\u99a8\u63d0\u793a","\u7fa4\u6807\u7b7e\u6570\u76ee\u5df2\u8fbe\u4e0a\u9650");
else{var b=a.str.trim(a("ui-ipt-addTag").value);b.length>0&&c(b)}});var e=false;a.e.add(b,"click",y=function(c){var b=c.target;if(b.tagName.toLowerCase()==="em"&&!e)if(g.callClientAPI("IsSelfOnline")){var d=b.parentNode,f=d.firstChild.textContent,q=d.getAttribute("tid");e=true;j.set_group_more_info({param:{gc:m,tagID:q},succ:function(){n--;e=false;var c=a.dom.getNode("a",{href:"javascript:;","class":"temp-tag element-invisible tag-wrap","aria-label":"\u5df2\u5220\u9664",tabindex:"2"});c.innerHTML=
d.innerHTML;d.parentNode.insertBefore(c,d);c.focus();v();a.dom.remove(d);delete i.qunTags[f];c=(a.dom.queryClassAll("js-tag","a",a("ui-tags"))||[]).length;a.oop.notifyObservers(o,"onTagChange",{action:"del",tagID:q,total:c});z();l("TAGS_DELETE_SUCC")},err:function(a){e=false;switch(a.ec){case 17:a="\u60a8\u6ca1\u6709\u6743\u9650\u5220\u9664\u7fa4\u6807\u7b7e";break;case 19:a="\u8be5\u7fa4\u6807\u7b7e\u5df2\u88ab\u5220\u9664\u6216\u4e0d\u5b58\u5728";break;case 9999:a="\u64cd\u4f5c\u8d85\u65f6\u4e86";
break;default:a="\u5220\u9664\u7fa4\u6807\u7b7e\u51fa\u9519\u4e86"}g.showTips(a)}})}else g.showTips("\u60a8\u5df2\u7ecf\u5904\u4e8e\u79bb\u7ebf\u72b6\u6001\uff0c\u8bf7\u4e0a\u7ebf\u540e\u518d\u6b21\u5c1d\u8bd5");c.preventDefault()})}function G(){if(i.hasPermission("addTag"))a("editTags-panel").style.display="block",E();else{var c=s;c.length<=0?a.css.addClass(a("viewTags"),"tags-empty"):(a.insertTags(a("viewTags"),c,u),a("viewTags").firstElementChild.setAttribute("tabindex","2"));a("viewTags-panel").style.display=
"block"}c=i.getRoleType()===B;l("TAGS_INITPAGE1",{v:c?1:0});l("TAGS_INITPAGE2")}function H(a,b){j.nicks({type:"GET",param:{u:a.join("-")},succ:function(a){for(var a=a.ns||[],c={},e=0;e<a.length;e++){var C=String(a[e].u),h=a[e].n;c[C]=h;if(C===i.uin)i.nick=h}b(c)},err:function(){b()}})}var I=function(){var c=g.getClientVersion();return function(b){var d={flag1:m,ver:c};if(typeof b==="object"&&!("v"in b)&&"aId"in b)b=a.bom.getHash("from"),d.v=b&&b==="create"?1:0;return d}}(),l=a.report.ReportFactory({config:{TAGS_FREQ_24H:242625},
getDefaultOptFn:I}),o={};B="visitor";n=0;x=void 0;y=void 0;var i=function(){var c={},b={visitor:[],member:[],admin:["addTag","delTag"]};c.hasPermission=function(c){return a.array.indexOf(b[this.role],c)!==-1?true:false};c.setRole=function(a){c.role=a===1?"member":a>1?"admin":"visitor"};c.getRoleType=function(){return this.role};c.uin=a.cookie.uin();c.qunTags={};return c}();u=0;t=2;m=void 0;s=void 0;m=parseInt(a.bom.getHash("groupuin"),10);a.convertHSLtoRGB=function(a,b,d){a/=360;if(d===0)b=d=a=0;
else if(b===0)b=d=a=d;else{var b=d<=0.5?d*(1+b):d+b-d*b,d=2*d-b,f=[];f.push(a+1/3);f.push(a);f.push(a-1/3);a=[];a.push(0);a.push(0);a.push(0);for(var e=0;e<3;e++)f[e]<0&&(f[e]+=1),f[e]>1&&(f[e]-=1),a[e]=6*f[e]<1?d+(b-d)*f[e]*6:2*f[e]<1?b:3*f[e]<2?d+(b-d)*(2/3-f[e])*6:d;b=parseInt(a[0]*255,10).toString(16);d=parseInt(a[1]*255,10).toString(16);a=parseInt(a[2]*255,10).toString(16);b.length===1&&(b="0"+b);d.length===1&&(d="0"+d);a.length===1&&(a="0"+a)}return"#"+b+d+a};w=24;a.insertTags=function(c,b,
d){var f=[],e,i,h=0,g=b.length;if(d===1){b=r.genRandomArray(b);for(h=0;h<g;h++)f.push(a.insertTags.tmpl(d,{title:b[h]}))}else if(d===u)for(h=0;h<g;h++)e=Math.random()*360,i=a.convertHSLtoRGB(e,0.5,0.89),e=a.convertHSLtoRGB(e,0.7,0.6),f.push(a.insertTags.tmpl(d,{title:b[h],bdColor:e,bgColor:i}));else if(d===t)for(h=0;h<g;h++)f.push(a.insertTags.tmpl(d,b[h]));c.innerHTML=f.join("")};a.insertTags.tmpl=function(a,b){if(a===u)return r.tmpl('<span class="tag tag-wrap" style="background-color:<%=bgColor%>;border:1px solid <%=bdColor%>;" tabindex="-1"><%=title%></span>',
b);else if(a===1)return r.tmpl('<a class="tag-wrap js-tag" href="javascript:void(0)" tabindex="-1"><span class="tag"><%=title%></span></a>',b);else if(a===t){var d="",f="";i.hasPermission("delTag")?(d=" can-delete",f=' aria-label="del\u952e\u5220\u9664"'):(d="<%=uin==$.cookie.uin()?' can-delete':''%>",f="<%=uin==$.cookie.uin()?' aria-label=\"del\u952e\u5220\u9664\"':''%>");return r.tmpl('<a hideFocus="true" class="tag-wrap js-tag'+d+'" tid="<%=tid%>" title="<%=nick%>\uff08<%=uin%>\uff09\u5f20\u8d34" uin="<%=uin%>" href="javascript:void(0)"'+
f+' tabindex="-1"><span class="tag"><%=tname%></span><em title="\u5220\u9664"></em></a>',b)}};var v=function(){var c=null;return function(){var b=document.activeElement;if(c!==b){if(c&&(c&&a.css.removeClass(c,"hover"),a.css.hasClass(c,"temp-tag"))){var d=c;d.nextSibling?d.nextSibling.setAttribute("tabindex","2"):d.parentNode.firstElementChild&&d.parentNode.firstElementChild.setAttribute("tabindex","2");a.dom.remove(c)}a.css.addClass(b,"hover");c=b}}}(),p={keyup:function(c){var b=document.activeElement,
d;c.keyCode===46?a.css.hasClass(b,"can-delete")&&a.e.trigger(b.lastChild,"click"):c.keyCode>=37&&c.keyCode<=40?a.css.hasClass(b,"tag-wrap")&&(d=c.keyCode===38||c.keyCode===37?"up":"down",c=b[d==="up"?"previousElementSibling":"nextElementSibling"],!c&&(c=b.parentNode[d==="up"?"lastElementChild":"firstElementChild"]),c.setAttribute("tabindex","2"),c&&c.focus(),b.setAttribute("tabindex","-1")):c.keyCode===9&&a.css.hasClass(b,"tag-wrap")&&v();v()},keydown:function(c){var b=document.activeElement;c.keyCode===
13&&(b.id==="ui-ipt-addTag"?a.e.trigger(a("ui-addTag"),"click"):a.css.hasClass(b,"tag-wrap")&&b.parentNode.id==="ui-hotTags"&&a.e.trigger(b.firstElementChild,"click"))},click:function(){v()}};o.init=function(c,b){a.e.add(document,"keyup",p.keyup);a.e.add(document,"keydown",p.keydown);a.e.add(document,"click",p.click);var d=parseInt(a.bom.getHash("groupuin"),10);if(isNaN(d))a.oop.notifyObservers(o,"getTagsFailed");else{m=d;i.setRole(b.flag);var f={};a.oop.extend(f,b.ns||{});var d=[],e=0,g=b.tags||
[],h=[],j=null;if(i.hasPermission("addTag")){for(;e<g.length;e++){var j=g[e],k=String(j.u);f[k]||d.push(k);h.push({uin:k,tname:j.tag,tid:j.sTid,nick:f[k]});i.qunTags[a.str.decodeHtml(j.tag)]=1}D.toggle("qun-tag",g.length)}else for(e=0;e<g.length;e++)h.push(g[e].tag);s=h;n=g.length;G();j=h=g=null;i.hasPermission("addTag")&&(d.push(i.uin),H(d,function(b){b&&a.oop.extend(f,b);for(var b=a.dom.queryClassAll("tag-wrap","a","ui-tags"),c=0;c<b.length;c++){var d=b[c].getAttribute("uin");b[c].setAttribute("title",
a.str.decodeHtml(f[d])+"\uff08"+d+"\uff09\u5f20\u8d34")}}))}l("TAGS_PV")};o.destroy=function(){a.e.remove(document,"keyup",p.keyup);a.e.remove(document,"keydown",p.keydown);a.e.remove(document,"click",p.click);var c=a("ui-tags");a.e.remove(a("ui-addTag"),"click",x);a.e.remove(c,"click",y)};return o});
