define("modules/model/list",[],function(){function k(){}function d(){return a}function c(e){a=e;g={};e.forEach(function(e){g[e.filepath]=e})}function i(e){a.unshift(e);g[e.filepath]=e;a.sort(function(e,a){a.createtime||console.warn("createtime\u6ca1\u6709\u503c");e.createtime||console.warn("createtime\u6ca1\u6709\u503c");return a.createtime-e.createtime});return a}function b(e,a){var b=g[e.filepath];if(a=="rename"&&b)b.filename=e.filename;if(a=="permanent"&&b){b.remotetype=1;b.can_forever=false;b.style_istemp=
"";var f=b.filepath,h=e.fp;b.filepath=h;g[h]=b;delete g[f]}}function h(){return g}function f(e){var e=g[e],b=a.indexOf(e);a.splice(b,1);delete g[e.filepath];return a}var a=[],g={};return function(){var e={};e.init=k;e.method={};e.method.setListData=c;e.method.addListData=i;e.method.updateListData=b;e.method.removeListData=f;e.method.getListDataMap=h;e.method.getListData=d;return e}()});
define("modules/model/box",[],function(){function k(e){j=e}function d(e){for(var b=0;b<e.length;b++){var a=e[b];l[a.filepath]||(p.push(a),l[a.filepath]=a)}}function c(e){n=e;j.local.clist.set(n)}function i(e){for(var b=0;b<e.length;b++){var a=e[b];!l[a.filepath]&&!l[a.id]&&(p.push(a),a.filepath&&(l[a.filepath]=a),a.id&&(l[a.id]=a))}}function b(e){var a=l[e];if(a)a.isRemoved=true,delete l[e],e=p.indexOf(a),e>=0&&p.splice(e,1)}function h(e){g_debug("updatePlistItem status=["+e.status+"]");if(e){var a=
l[e.id];if(!a)if((a=l[e.filepath])&&a.type.indexOf("upload")>=0&&e.type.indexOf("upload")>=0&&a.status!=e.status)l[a.id]=a;else if(a&&e.type=="download"){l[a.id]=a;if(a.isRemoved&&e.status!="remove")a.isRemoved=false;e.status!="remove"&&p.indexOf(a)<0&&p.unshift(a)}else a=null;if(a){e.filepath&&(l[e.filepath]=a);for(var b in e)b==="createtime"&&a.createtime||b==="task_starttime"&&a.task_starttime||(a[b]=e[b]);a.status.indexOf("complete")>=0&&(b=p.indexOf(a),b>=0&&(l[a.filepath]=null,p.splice(b,1),
n.unshift(a),j.local.clist.set(n),p[a.filepath]=null));return a}else return g_debug("\u51fa\u9519\u4e86\uff0c\u600e\u4e48\u53ef\u80fd\u51fa\u73b0\u4e0d\u5b58\u5728\u7684plist item"),null}}function f(e,b){for(var j=[],f=0;f<e.length;f++){var g=e[f];b?j.push(a(g)):(g=h(g))&&j.push(g)}return j}function a(a){var e=l[a.id];if(!e&&(e=l[a.filepath]))e&&e.type.indexOf("upload")>=0&&a.type.indexOf("upload")>=0&&e.status!=a.status?(a.id&&(l[a.id]=e),console.log("new task \u53d1\u73b0\u7eed\u4f20 id["+e.id+
"] status["+e.status+"]")):a.type!="download"&&(e=null);if(e){l[a.id]=e;for(var b in a)e[b]=a[b];return e}else return p.unshift(a),a.id&&(l[a.id]=a),a.filepath&&(l[a.filepath]=a),a}function g(){return{plist:p,clist:n}}function e(){for(var a=[],e=0;e<n.length;e++)a.push(n[e]);n=[];j.local.clist.clear();return a}var j,n=[],p=[],l={};return function(){var j={};j.init=k;j.method={};j.method.setContinueTask=d;j.method.setClist=c;j.method.setPlist=i;j.method.updatePlist=f;j.method.updatePlistItem=h;j.method.addNewTask=
a;j.method.getBoxData=g;j.method.removePlistItem=b;j.method.clearClist=e;window.g_plistMap=l;window.g_plist=p;return j}()});define("modules/app.model",["./model/list","./model/box"],function(k,d){function c(h,f,a){b.info=h;b.local=f;b.client=a;k.init(b);d.init(b)}var i={},b={evt:{}};return function(){for(var h in k.method)i[h]=k.method[h];for(h in d.method)i[h]=d.method[h];i.init=c;i.evt=b.evt;return i}()});
define("util/date",[],function(){function k(a){return Math.ceil(a/86400)}function d(a){a=n(a);return a.getFullYear()!=l.getFullYear()?false:a.getMonth()!=l.getMonth()?false:a.getDate()!=l.getDate()?false:true}function c(a){var a=n(a),e=false;d(a)||(a=new Date(l.getFullYear(),l.getMonth(),l.getDate())-a,e=a>0&&a<864E5);return e}function i(a){var a=n(a),e=false;d(a)||(a=new Date(l.getFullYear(),l.getMonth(),l.getDate())-a,e=a>=0&&a<=864E5);return e?"\u6628\u5929":"\u524d\u5929"}function b(a){var a=
n(a),e=false;d(a)||(a=new Date(l.getFullYear(),l.getMonth(),l.getDate())-a,e=a>0&&a<1728E5);return e}function h(e){var e=n(e),b=a(l);return e>b?true:false}function f(a){a=n(a);return a.getYear()!=l.getYear()?false:true}function a(a){var a=n(a),e=a.getDay();e===0&&(e=7);e-=1;return new Date(a.getTime()-e*864E5)}function g(){}function e(a){var e=n(a),a=e.getFullYear(),b=e.getMonth()+1,e=e.getDate();return a+"-"+b+"-"+e}function j(a){a=n(a);a=(new Date).getTime()-a.getTime();a=parseInt(a/36E5,10);a<
1?a="\u521a\u521a":a+="\u5c0f\u65f6\u524d";return a}function n(a){var e=a;typeof a==="string"&&(e=new Date(a));typeof a==="number"&&(e=new Date(a*1E3));return e}function p(a){var e;typeof a=="number"?e=new Date(a*1E3):a instanceof Date&&(e=a);return d(e)?"\u4eca\u5929":b(e)?"\u6700\u8fd1\u4e09\u5929":h(e)?"\u4e00\u5468\u5185":f(e)?e.getFullYear()+"\u5e74"+(e.getMonth()+1)+"\u6708":e.getFullYear()+"\u5e74"}var l=new Date;l.getFullYear();return function(){var l={};l.dayStr=p;l.getDateStr=e;l.getDOY=
g;l.getMOW=a;l.isToday=d;l.isYesterday=c;l.isThisWeek=h;l.isThisYear=f;l.getHourStr=j;l.isLast3days=b;l.strYesterdayOrPre=i;l.getExpriesDayNum=k;return l}()});
define("util/fileicon",[],function(){return{getFileIcon:function(k){var d="unknow",c={xls:/xls|xlsx/i,pdf:/pdf/i,ppt:/ppt|pptx/i,word:/doc|docx|wps/i,txt:/txt/i,pic:/jpg|jpeg|jpgx|gif|bmp|png/i,music:/mp3|wma|midi|aac/i,video:/mp4|rm|rmvb|mpeg|mov|avi|3gp|amv|dmv|flv|wmv|qsed|asf/i,zip:/rar|zip|tar|cab|uue|jar|iso|7z|ace|lzh|arj|gzip|bz2/i,code:/ink|torrent|url|vbs|tif|w3g|vbe|ssf|dll|mht|rcd|bat|sav|dat|cmd|ttf|xml|vob|sgs|mhw|js|html|htm|css/i,exe:/exe|msi|apk|ipa/i},i;for(i in c)if(c[i].test(k)){d=
i;break}return d}}});define("util/fileType",[],function(){return{getFileType:function(k){var d="\u5176\u4ed6",c={"\u6587\u6863":/doc|docx|ppt|pptx|xsl|xslx|xls|xlsx|pdf|txt|wps/i,"\u56fe\u7247":/jpg|jpeg|jpgx|gif|bmp|png/i,"\u97f3\u4e50":/mp3|wma|midi|aac/i,"\u89c6\u9891":/mp4|rm|rmvb|mpeg|mov|avi|3gp|amv|dmv|flv|wmv|qsed/i,"\u538b\u7f29\u5305":/rar|zip|tar|cab|uue|jar|iso|7z|ace|lzh|arj|gzip|bz2/i},i;for(i in c)if(c[i].test(k)){d=i;break}return d}}});
define("util/fileSize",[],function(){return{getFileSize:function(k){var d={fLen:3};if(typeof k!="number")return"";for(var c="B,KB,MB,GB,TB,PB".split(",");k>1024;)k/=1024,c.shift();k>=1E3&&(k/=1024,c.shift());var i=2,b=100;if(d&&d.len)i=d.len;i<0&&(i=0);b=Math.pow(10,i);k=Math.floor(k*b)/b;if(d&&d.fLen)i=k.toString().indexOf("."),k.toString().length<=d.fLen?(i=parseInt(k,10).toString().length,k=k.toFixed(d.fLen-i)):d.fLen<k.toString().length&&(k=k.toString(),k=i>0&&i<3?k.substr(0,4):k.substr(0,3));
d=k.toString().replace(/\.0+$/,"");d+=c[0];k===0&&(d=0);return d}}});
define("util/fileIcon",[],function(){return{getFileIcon:function(k){var d="unknow",c={xls:/xls|xlsx/i,pdf:/pdf/i,ppt:/ppt|pptx/i,word:/doc|docx|wps/i,txt:/txt/i,pic:/jpg|jpeg|jpgx|gif|bmp|png/i,music:/mp3|wma|midi|aac/i,video:/mp4|rm|rmvb|mpeg|mov|avi|3gp|amv|dmv|flv|wmv|qsed|asf/i,zip:/rar|zip|tar|cab|uue|jar|iso|7z|ace|lzh|arj|gzip|bz2/i,code:/ink|torrent|url|vbs|tif|w3g|vbe|ssf|dll|mht|rcd|bat|sav|dat|cmd|ttf|xml|vob|sgs|mhw|js|html|htm|css/i,exe:/exe|msi|apk|ipa/i},i;for(i in c)if(c[i].test(k)){d=
i;break}return d}}});
define("modules/client_hummer",[],function(){function k(){var b=top.external&&top.external.CallHummerApi;if(b){var a;try{a=b.apply(this,arguments),a=JSON.parse(a)}catch(g){return false}return a}return false}function d(b,a,g,e){if(!top||typeof top.external!=="object"||!("CallHummerApi"in top.external))return b="CallHummerApi\u63a5\u53e3\u4e0d\u5b58\u5728!",h&&h&&(b+=h),top?typeof top.external!=="object"?b+="!top.external is not object":"CallHummerApi"in top.external||(b+="CallHummerApi not in top.external"):b+=
"|top is null",c({type:"error",msg:b,url:"src:",report:"ERR_CLT_HUMMERAPI_NOT_EXIST"}),top&&top.confirm?top.confirm(a):true;typeof g==="undefined"&&(g=2);typeof e==="undefined"&&(e="\u63d0\u793a");a={text:a,iconType:g,title:e};a=JSON.stringify(a);if((b=k("Window."+b,a))&&b.errorCode===0&&"ret"in b)return b.ret}var c=window.g_log,i={},b=null,h=window.external&&window.external.CallHummerApi&&window.external.CallHummerApi("IM.GetVersion");i.IsOnline=function(){return window.G_DEBUG?true:k("Contact.IsOnline")?
k("Contact.IsOnline").online:false};i.OpenContactInfoCard=function(b,a){return k("Contact.OpenContactInfoCard",'{ "uin" : "'+b+'", "tabId" : '+(a||1)+" }")};i.GetNickName=function(f){if(b)return b;var a={uin:f+""},a=JSON.stringify(a);if((a=k("Contact.GetNickName",a))&&a.errorCode===0&&a.nickName)b=a.nickName;return!b?f:b};i.getClientKey=function(){return k("IM.GetClientKey")};i.confirm=function(b,a,g){return d("Confirm",b,a,g)};i.alert=function(b,a,g){return d("Alert",b,a,g)};i.preview=function(b){b+=
"&pictype=scaled&size=1024*1024";k("Misc.OpenWebPic",'{"url":"'+b+'"}')};return i});
define("util/group",["../modules/client_hummer"],function(){function k(c,i,b){c.sort(b);for(var b={},h=[],f=0;f<c.length;f++){var a=c[f],g=i(a);b[g]||(b[g]=[]);b[g].push(a)}for(var e in b)h.push({title:e,data:b[e]});return h}function d(c,i,b,h){for(var f=[],a=0;a<b.length;a++)f[a]={title:b[a],data:[]};c.sort(h);for(a=0;a<c.length;a++)b=c[a],h=i(b),f[h].data.push(b);c=[];for(a=0;a<f.length;a++)f[a].data.length>0&&c.push(f[a]);return c}return{group:function(c,i,b,h,f){c=c.map(function(a){return a});
if(i==="fixed")return d(c,b,h,f);else if(i==="free")return k(c,b,f)}}});
define("util/groupData",["./group"],function(k){function d(b){return k.group(b,"fixed",function(a){return a.size_type},"\u5927\u4e8e100MB,50-100MB,10-50MB,1-10MB,100KB-1MB,0-100KB".split(","),function(a,b){var e=b.filesize-a.filesize;e===0&&(e=b.createtime-a.createtime);return e})}function c(b){return k.group(b,"free",function(a){return a.day_str},null,function(a,b){return b.createtime-a.createtime})}function i(b){return k.group(b,"fixed",function(a){a=a.type_str;return a=="\u6587\u6863"?0:a=="\u56fe\u7247"?
1:a=="\u97f3\u4e50"?2:a=="\u89c6\u9891"?3:a=="\u538b\u7f29\u5305"?4:5},"\u6587\u6863,\u56fe\u7247,\u97f3\u4e50,\u89c6\u9891,\u538b\u7f29\u5305,\u5176\u4ed6".split(","),function(a,b){return b.createtime-a.createtime})}function b(b){for(var b=k.group(b,"free",function(a){return a.uploadnick+a.uploaduin},null,function(a,b){var g=a.uploadnick.toUpperCase()+a.uploaduin,f=b.uploadnick.toUpperCase()+a.uploaduin,g=g.localeCompare(f);g===0&&(g=b.createtime-a.createtime);return g}),a=0;a<b.length;a++){var g=
b[a];g.uin=g.data[0].uploaduin;g.nick=g.data[0].uploadnick;g.title=g.data[0].uploadnick;if(a>0&&b[a-1]&&b[a-1].nick==g.nick)g.title=g.nick+" ("+g.uin+")",g=b[a-1],g.title=g.nick+" ("+g.uin+")"}return b}function h(b){return k.group(b,"fixed",function(a){a=a.downloadtimes;return a<10?5:a<30?4:a<50?3:a<100?2:a<500?1:0},"500\u6b21\u4ee5\u4e0a,100-500\u6b21,50-100\u6b21,30-50\u6b21,10-30\u6b21,10\u6b21\u4ee5\u4e0b".split(","),function(a,b){var e=b.downloadtimes-a.downloadtimes;e===0&&(e=b.createtime-a.createtime);
return e})}return{groupData:function(f,a){a||(a={});var g=a.sortBy;g||(g="time");var e;g==="time"?e=c(f):g==="uploader"?e=b(f):g==="type"?e=i(f):g==="size"?e=d(f):g==="download"&&(e=h(f));return e}}});
define("util/xss",[],function(){var k=function(){var d=/"|&|'|<|>|[\x00-\x20]|[\x7F-\xFF]|[\u0100-\u2700]/g,c=/&\w+;|&#(\d+);/g,i={"&lt;":"<","&gt;":">","&amp;":"&","&nbsp;":" ","&quot;":'"',"&copy;":""};return{encodeHtml:function(b){b=b!=void 0?b:"";return typeof b!="string"?b:b.replace(d,function(b){var b=b.charCodeAt(0),f=["&#"];f.push(b==32?160:b);f.push(";");return f.join("")})},decodeHtml:function(b){b=b!=void 0?b:"";b=typeof b!="string"?b:b.replace(c,function(b,f){var a=i[b];a==void 0&&(a=
isNaN(f)?b:String.fromCharCode(f==160?32:f));return a});b=b.replace(/&#x2028;/g,"\u2028");return b=b.replace(/&#x2029;/g,"\u2029")}}}();return{xssHtml:k.encodeHtml,xssNoEsc:k.decodeHtml}});define("util/parameter",[],function(){return{getParameter:function(k){k=location.href.match(RegExp("(\\?|#|&)"+k+"=([^&#]*)(&|#|$)"));return!k?"":k[2]}}});
define("util/util","./date,./fileicon,./fileType,./fileSize,./fileIcon,./group,./groupData,./xss,./parameter".split(","),function(){for(var k=arguments,d={},c=0;c<k.length;c++){var i=k[c],b;for(b in i)d[b]=i[b]}return d});
define("modules/local",[],function(){function k(){if(!window.g_flag_local_enable)return null;if(!p){var b=a[e];if(b){var b=JSON.parse(b),j=b.flist;if(j){var g=j.length,f=[];l={};for(var c=0;c<g;c++){for(var h={},i=j[c],n=0;n<r;n++)h[q[n]]=i[n];if(h.ufs===-1)h.ufs=h.fs;f.push(h);l[h.fp]=h}b.flist=f}p=b}}return p}function d(b){p=b;try{var j;if(b.flist){l={};var g={flist:[]},f=b.flist,h;for(h in b)h!="flist"&&(g[h]=b[h]);var c=f.length;for(h=0;h<c;h++){var i=[],n=f[h];l[n.fp]=n;for(var d=0;d<r;d++)q[d]==
"ufs"&&n.ufs==n.fs?i.push(-1):i.push(n[q[d]]);g.flist.push(i)}j=JSON.stringify(g)}else j=void 0;a[e]=j}catch(k){console.error(k);try{a.clear(),a[e]=JSON.stringify(b)}catch(o){}}}function c(){if(!window.g_flag_local_enable)return null;if(!o){var b=a[j];o=b?JSON.parse(b):[]}return o}function i(b){o=b;try{var e=JSON.stringify(b);a[j]=e}catch(g){console.error(g);try{a.clear(),a[j]=JSON.stringify(b)}catch(f){}}}function b(){if(!window.g_flag_local_enable)return null;if(!m){var b=a[n];m=window.g_i_ifFileExist&&
b?JSON.parse(b):{}}return m}function h(b){m=b;try{var e=JSON.stringify(b);a[n]=e}catch(j){console.error(j);try{a.clear(),a[n]=JSON.stringify(b)}catch(g){}}}var f={},a=window.localStorage,g,e,j,n,p,l,o,m,q="dt,exp,fn,fp,fs,mt,t,ufs,uin,ut".split(","),r=q.length;f.init=function(h){g=h;if(a.gs_version!=12)a.clear(),a.gs_version=12;e="cgi_12_"+g.groupid+"_"+g.uin;j="clist_12_"+g.groupid+"_"+g.uin;n="lp_12_"+g.groupid+"_"+g.uin;f.lpData=b();f.clistData=c();f.cgiData=k();console.log("local init");console.log("lpData="+
JSON.stringify(f.lpData))};f.version=12;f.cgi={};f.cgi.get=k;f.cgi.set=d;f.cgi.update=function(a){var b=a.fp;if(l&&l[b]){var b=l[b],e;for(e in a)b[e]=a[e];d(p)}};f.cgi.remove=function(a){if(p&&p.flist&&l){var b=p.flist;if(a=l[a])a=b.indexOf(a),a>=0&&(b.splice(a,1),d(p))}};f.clist={};f.clist.get=c;f.clist.set=i;f.clist.add=function(a){o||(o=[]);o.unshift(a);i(o)};f.clist.clear=function(){delete a[j];delete a[n];m=o=null};f.lp={};f.lp.get=b;f.lp.set=h;f.lp.add=function(a,b){m||(m={});m[a]=b;h(m)};f.lp.remove=
function(a){m&&m[a]&&delete m[a];h(m)};f.clearAll=function(){for(var b in a)delete a[b]};f.key={};f.key.cgi=e;f.key.clist=j;f.key.lp=n;return f});
define("modules/cleanData",["../util/util","./local"],function(k,d){function c(a,g,e){var j=d.lp.get();if(j&&j[a.fp]&&a)a._localpath=j[a.fp];j=0;if(a&&a.filename){if(a.filepath)a.filepath=a.filepath.replace(/\\\//g,"/");if(!a.remotetype)switch(a.busid){case 102:a.remotetype=h;break;case 104:case 105:a.remotetype=f;break;default:a.remotetype=h}if(a.uploadsize<a.filesize){if(a.uploaduin===g.uin){a.type="continueupload";a.status="continue";a.is_continue_upload=true;a.task_starttime=a.createtime;a.styles=
"upload pause";a.completesize=a.uploadsize;a.csize_str=k.getFileSize(a.uploadsize);a.c_percent=0;if(a.uploadsize&&a.filesize)a.c_percent=100*a.uploadsize/a.filesize;a.not_complete=true;j=1}}else{j=2;a.auditflag>0&&console.warn("auditFlag",a);var c=a.filename,i=a.filesize,l=a.createtime;if(!a.downloadtimes)a.downloadtimes=0;var o=c.lastIndexOf(".");o>=0?(a.filename_name=c.substr(0,o),a.filename_suf=c.substr(o)):(a.filename_name=c,a.filename_suf="");a.file_icon=k.getFileIcon(a.filename_suf);a.isAdmin=
e||a.uploaduin===g.uin?true:false;a.filesize_str=k.getFileSize(i);a.createtime_str=k.getDateStr(l);a.day_str=k.dayStr(l);a.type_str=k.getFileType(a.filename_suf);if(a.type_str==="\u56fe\u7247"&&(j=3,!g.isVisitor))a.can_preview=true;if(b(a.filename_suf.split(".")[1],a.filesize)&&(j=3,!g.isVisitor))a.can_preview=true;if(a.remotetype===f&&a.isAdmin)a.can_forever=true;if(a.day_str==="\u4eca\u5929")a.createtime_str=k.getHourStr(l);if(a.day_str==="\u6700\u8fd1\u4e09\u5929")a.createtime_str=k.strYesterdayOrPre(l);
g=0;i<102400?g=5:i<1048576?g=4:i<10485760?g=3:i<52428800?g=2:i<104857600&&(g=1);e=[];if(a.isAdmin)a.can_delete=true,a.can_rename=true,e.push("can_delete=1 "),e.push("can_rename=1 ");a.can_preview&&e.push("can_preview=1 ");a.can_forever&&e.push("can_forever=1 ");a.can_do=e.join("");a.style_disable_more="";if(a.can_do==="")a.style_disable_more="disable_more";a.size_type=g;if(!a.style_istemp)a.style_istemp="";if(!a.style_issucc)a.style_issucc="";a.expire_str="";a.file_title=a.filename;if(a.remotetype===
f)a.style_istemp="temp",a.expire_str=k.getExpriesDayNum(a.ttl)+"\u5929\u540e\u5230\u671f",a.file_title+=" (\u4e34\u65f6\u6587\u4ef6\uff1a\u5269\u4f59"+k.getExpriesDayNum(a.ttl)+"\u5929)"}return j}}function i(a,b){var e=a||{},j=e.flist,f={},h=e.name_list;h||(h=[]);h.forEach(function(a){f[a.u]=a.n});b.uins=f;var h=e.ismanager,i=e.role,d=false,e=e.isPublic;i&&(h=0,i>=4?h=1:i===1&&e===1&&(d=true));j||(j=[]);e={isVisitor:d,listData:[],boxData:[],imgData:[]};for(i=0;i<j.length;i++){d=j[i];if(d.fn){d.filename=
d.fn;d.filename_esc=k.xssNoEsc(d.filename);d.filepath="/"+d.t+d.fp;if(d.lp)d.localname=k.xssNoEsc(d.lp),d.localname=d.localname.replace(/\\|\//g,"\\\\");d.filesize=d.fs;d.uploaduin=d.uin;d.busid=d.t;d.ttl=Math.floor(new Date(d.exp*1E3)-new Date)/1E3;d.createtime=d.ut;d.updatetime=d.mt;d.downloadtimes=d.dt;d.uploadnick=f[d.uin];d.uploadsize=d.ufs;if(d.ufs===null)d.uploadsize=d.filesize}var m=c(d,b,h);if(m==1)e.boxData.push(d);else if(m==2||m==3)e.listData.push(d),m==3&&e.imgData.push(d)}return e}var b=
function(){var a=window.external&&window.external.getPreviewSuffixConfig&&window.external.getPreviewSuffixConfig();a===null&&(a={content:[]});if(typeof a==="string")try{a=JSON.parse(a)}catch(b){}typeof a!=="object"&&(a={content:[]});var e={};if(a=a.content)for(var j=0,f=a.length;j<f;j++){var h=a[j].maxsize;a[j].suffix.split(".").forEach(function(a){a&&(e[a]=h)})}return function(a,b){var j;if((j=e[a])&&b<=j)return true}}(),h=1,f=2;return function(){var a={};a.cleanItem=c;a.cleanArray=i;return a}()});
define("modules/view/list/setThumb",[],function(){function k(b){b instanceof Array?b.forEach(function(b,f){setTimeout(function(){d(b)},parseInt(f/2,10)*300)}):d(b)}function d(b){i++;if(!(b.filesize>20971520)){var h=document.getElementById("list_"+b.filepath),f=b.thumbUrl;if(f&&!c[f]){f+="&pictype=scaled&size=50*50";var a=new Image;a.onload=function(){if(a.complete){if(h&&b.thumbUrl){var g=h.querySelector(".c0 div");g.className="thumb";console.log("img succ  "+f);g.style.backgroundImage="url("+f+")";
g_report("img_thumb_load_succ")}i--}};a.onerror=function(){console.log("img error  "+f);i--};a.src=f;g_report("img_thumb_load")}}}var c={},i=0;return function(){var b={};b.setThumb=k;return b}()});define("util/domCache",[],function(){function k(b,h){var f=c.indexOf(b);f>=0?i[f]=h:(c.push(b),i.push(h))}function d(b){b=c.indexOf(b);return b>=0?i[b]:null}var c=[],i=[];return function(){var b={};b.add=k;b.get=d;return b}()});
define("modules/view/list",["../../util/util","../cleanData","./list/setThumb","../../util/domCache"],function(k,d,c,i){function b(){n.innerHTML="";n.classList.add("empty");l.innerHTML="\u6682\u65e0\u6587\u4ef6"}function h(b,e){n.scrollTop=0;for(var j=n.innerHTML="",g=0,h=false,c,d=0;d<b.length;d++){var l=b[d],k=l.title,m=l.uin||d,o=l.data;g>20&&(h=true);var q=document.createElement("div");e.target&&e.target==l.uin&&(c=d);q.innerHTML=h||e.target&&l.uin&&e.target!=l.uin?"<div class='group_title collapse' data-action='group_toggle' id='group_"+
d+"' name='group_"+m+"'><i></i>"+k+"</div>":"<div class='group_title' data-action='group_toggle' id='group_"+d+"' name='group_"+m+"'><i></i>"+k+"</div>";m=document.createElement("div");m.innerHTML=h||e.target&&l.uin&&e.target!=l.uin?"<div class='group collapse'></div>":"<div class='group open'></div>";m=m.childNodes[0];n.appendChild(q.childNodes[0]);n.appendChild(m);for(q=0;q<o.length;q++){var r=o[q],x=i.get("list_"+r.filepath);x?(m.appendChild(x),f(x,r)):(x=document.createElement("div"),x.innerHTML=
a(r),m.appendChild(x.childNodes[0]))}o="";d===0&&(o="shown");j+=h||e.target&&l.uin&&e.target!=l.uin?"<div class='group_title_top collapse "+o+"' data-action='link_to' tid='group_"+d+"' id='tgroup_"+d+"'><i></i>"+k+"</div>":"<div class='group_title_top "+o+"' data-action='link_to' tid='group_"+d+"' id='tgroup_"+d+"'><i></i>"+k+"</div>";e.target||(g+=q)}n.scrollTop=c?26*c:0;n.classList.remove("empty");p.innerHTML=j}function f(b,e){var j=b.querySelector(".c1"),g,f;if(b.classList.contains("error"))f=
b.querySelector(".security"),g=f.onmouseover,f=f.onmouseout;var h=a(e),c=h.indexOf('<div class="c1">')+16,i=h.indexOf('<div class="c2">')-6,h=h.substr(c,i-c);if(j.innerHTML!=h&&(j.innerHTML=h,g))j=j.querySelector(".security"),j.onmouseover=g,j.onmouseout=f}function a(a){var b="";if(a._localpath)a.style_issucc="succ";var e=" "+a.style_issucc||"",j="img",g="",f="",h="",c='data-action="file_active"',i="",d=a.file_title;a.thumbUrl&&(g=' style="background-image:url('+a.thumbUrl+');"',j="thumb");a.file_icon===
"pic"&&a.can_preview&&(f=' title="\u9884\u89c8\u6587\u4ef6"',h=' data-action="img_preview"',c=' data-action="preview_filename"',i=" imgFile",d="\u9884\u89c8\u6587\u4ef6 : "+a.file_title);b+='<div class="file '+a.style_istemp+e+i+'" id="list_'+a.filepath+'"'+c+" >";b+='<div class="c9" data-action="file_check">';b+='<input type="checkbox" class="cbox"  data-action="file_check" aria-label="\u6587\u4ef6\u7c7b\u578b:'+a.type_str+",\u540d\u79f0"+a.file_title+'" tab-index="1"></div>';b+='<div class="c0 icon '+
a.file_icon+'">';b+='<div class="'+j+'"'+g+f+h+"></div><i></i></div>";b+='<div class="c1">';b+='<div class="filename" '+h+' title="'+d+'">';b+='<div class="name" '+h+">"+a.filename_name+"</div>";b+='<div class="suffix" '+h+">"+a.filename_suf+"</div>";b+='<div class="security" '+h+"></div>";b+='<div class="tempicon" title="\u4e34\u65f6\u6587\u4ef6:'+a.expire_str+'"></div>';b+="</div>";b+='<div class="file_info" '+h+">";b+='<span class="file_size" '+h+' title="\u6587\u4ef6\u5927\u5c0f:'+a.filesize_str+
'">'+a.filesize_str+"</span>";b+='<span class="file_dot" '+h+">.</span>";b+="<span  "+h+' title="\u4e0b\u8f7d\u6b21\u6570:'+a.downloadtimes+'\u6b21">';b+='<span class="downloadtime" '+h+">"+a.downloadtimes+"\u6b21\u4e0b\u8f7d</span>";b+="</span>";b+='<span class="uploader"  '+h+' title="\u4e0a\u4f20\u8005:'+a.uploadnick+'">';b+='<i class="uploader_name" data-action="go_uploader" upload_uin="'+a.uploaduin+'">'+a.uploadnick+"</i></span>";b+='<span class="uploadtime" '+h+' title="\u4e0a\u4f20\u65f6\u95f4:'+
a.createtime_str+'">';b+=a.createtime_str+"</span>";b+="</div>";b+="</div>";b+='<div class="c2">';b+='<div class="btn_group">';b+=a.style_issucc=="succ"&&window.g_i_openfolder?'<a href="javascript:void(0)" class="btn_left chakan" data-action="open_folder3" title="\u5728\u6587\u4ef6\u5939\u4e2d\u67e5\u770b"  tab-index="1" aria-label="\u67e5\u770b\u6587\u4ef6'+a.filename_name+'">\u67e5\u770b</a>':'<a href="javascript:void(0)" class="btn_left download" data-action="file_download" title="\u4e0b\u8f7d" tab-index="1" aria-label="\u4e0b\u8f7d\u6587\u4ef6'+
a.filename_name+'">\u4e0b\u8f7d</a>';b+='<a class="file_more" data-action="file_more" menu="file_menu" title="\u66f4\u591a"></a>';b+="</div>";b+="</div>";b+="</div>";return b}function g(e,g,f){e?q=e:e=q;f=e.length;if(!e||!e.length)b();else{e.length>0&&n.classList.remove("empty");for(var c=0;c<e.length;c++)var d=e[c];l.innerHTML="\u5171"+f+"\u4e2a\u6587\u4ef6";g?m=g.sortBy:g={sortBy:m};g.sortBy=="uploader"?n.classList.add("sortby_uploader"):n.classList.remove("sortby_uploader");f=k.groupData(e,g);
if(r){for(var d=g="",B=0,A=false,t=0;t<f.length;t++){var w=f[t],y=w.title,c=w.uin||t,w=w.data;B>20&&(A=true);A?(g+="<div class='group_title collapse' data-action='group_toggle' id='group_"+t+"' name='group_"+c+"'><i></i>"+y+"</div>",g+="<div class='group collapse'>"):(g+="<div class='group_title' data-action='group_toggle' id='group_"+t+"' name='group_"+c+"'><i></i>"+y+"</div>",g+="<div class='group open'>");for(c=0;c<w.length;c++)g+=a(w[c]);g+="</div>";B+=c;c="";t===0&&(c="shown");d+=A?"<div class='group_title_top collapse "+
c+"' data-action='link_to' tid='group_"+t+"' id='tgroup_"+t+"'><i></i>"+y+"</div>":"<div class='group_title_top "+c+"' data-action='link_to' tid='group_"+t+"' id='tgroup_"+t+"'><i></i>"+y+"</div>"}n.scrollTop=0;n.classList.remove("empty");n.innerHTML=g;p.innerHTML=d;o++;setTimeout(function(){n.scrollHeight<=n.clientHeight?p.classList.add("notfull"):p.classList.remove("notfull")},20);r=false;j.push("main","pageRender");if(!window.g_page_rendered)window.g_page_rendered=true,j.report("flag1=7809&flag2=1&flag3=57",
"main",{domStart:"1",cssLoad:"2",thirdLib:"3",mainStart:"4",cgiReturn:"5",pageRender:"6"});for(c=0;c<e.length;c++)d=e[c],f="list_"+d.filepath,i.add(f,document.getElementById(f))}else h(f,g)}}function e(a,e){document.getElementById("file_num").innerHTML=e&&e.length>0?"\u5171"+e.length+"\u4e2a\u6587\u4ef6":"\u6682\u65e0\u6587\u4ef6";var j=document.getElementById("list_"+a);if(j){var g=j.parentNode;g_remove_ease(j);setTimeout(function(){var a=g.childNodes.length,b=g.querySelectorAll(".remove");a-=b.length;
if(b=g.previousSibling){var e=document.getElementById("t"+b.id);if(a===0)a=g.parentNode,a.removeChild(g),a.removeChild(b),e.parentNode.removeChild(e)}},330)}(!e||e.length===0)&&b()}var j=window.TRecord,n=document.getElementById("file_list"),p=document.getElementById("group_top"),l=document.getElementById("file_num"),o=1,m,q,r=true;return function(){var a={};a.setThumb=c.setThumb;a.renderList=g;a.updateRowDiv=f;a.removeRow=e;return a}()});
define("modules/view/box",["../../util/util","../../util/domCache"],function(k,d){function c(a,b){var e=document.getElementById("box"),e=b?false:!e.classList.contains("open"),j=document.getElementById("box_num"),g=a,f="";a===0?(g="",e&&(f="hint")):a<10?f="small":a>=10&&a<100?f="big":a>=100&&(g="99+",f="ninety-nine-more");j.innerHTML=g;j.className="box_num "+f;a>0&&document.getElementById("box_list").classList.remove("empty");window.postMessage("print","*")}function i(a){var b=document.getElementById("box_list");
a===0?b.classList.add("empty"):b.classList.remove("empty")}function b(a){var b=document.getElementById("box_title");a===0?b.classList.add("empty"):b.classList.remove("empty")}function h(){q.classList.remove("open")}function f(){m=setTimeout(h,600)}function a(a){a=a.target.getBoundingClientRect();q.style.top=a.bottom+10+"px";q.style.left=a.left+"px";if(window.external&&window.external.CallHummerApi){var a=window.external.CallHummerApi("Contact.GetSelfUin"),b=window.external.CallHummerApi("IM.GetClientKey");
if(a)a=JSON.parse(a).uin;b&&(b=JSON.parse(b));if(b.clientKey){var b=b.clientKey,e="http://ptlogin2.qq.com/pcmgr_false_positives?";e+="clientuin="+a;e+="&clientkey="+b;r.href=e;q.classList.add("open")}}}function g(j,g){g_debug("updateBoxView plist.length=["+g.plist.length+"]");if(j){var h=false;console.debug("data",j);for(var d=0;d<j.length;d++){var l=j[d];if(l&&(l.status==="uploadcomplete"&&!h&&(setTimeout(function(){ctx.tasks.do_box_open()},10),h=true),e(l),l.securityattri&&l.securityattri!==2&&
(l=document.getElementById("list_"+l.filepath))&&!l.classList.contains("error")))l.classList.add("error"),l=l.querySelector(".security"),l.onmouseover=a,l.onmouseout=f}h=g.plist;l=[];console.log(client.getPlist());console.log("---------");console.log(h);for(d=0;d<h.length;d++)h[d]&&h[d].status&&h[d].status.indexOf("remove")<0&&h[d].status.indexOf("complete")<0&&h[d].status.indexOf("error")<0&&l.push(h[d]);d=g.clist;c(l.length);i(h.length+d.length);b(d.length)}}function e(a){if(!a||!a.status)console.warn("updateBoxRow obj=["+
a+"]");else{var b=d.get(a);if(!b||!b.parentNode)a=n(a),o.childNodes.length>0?o.insertBefore(a,o.childNodes[0]):o.appendChild(a);else if(a.status==="remove")g_remove_ease(b);else{var e="file2 ";window.g_i_openfolder&&(e+="file2_2 ");e+=a.styles;b.className=e;e=b.querySelector(".wording");b=b.querySelector(".bar");e.innerHTML=a.wording;b.style.width=a.c_percent>0?a.c_percent+"%":"0%"}}}function j(a,e){var j=a.plist,g=a.clist;j||(j=[]);g||(g=[]);e&&(s=false);if(s)c(j.length);else{var h;h=g;var f=document.getElementById("box_list");
if(h.length>=l){f.classList.add("overflow");for(var f=[],p=0;p<l;p++)f.push(h[p]);h=f}else f.classList.remove("overflow");h=j.concat(h);f=document.getElementById("box_list");for(p=0;p<h.length;p++){var k=h[p];if(k){var m=d.get(k);if(!m||!m.parentNode)k=n(k),m=f.firstChild,!m||k&&k.classList.contains("complete")?f.appendChild(k):f.insertBefore(k,m)}}c(j.length,true);s=true;i(j.length+g.length);b(g.length)}}function n(a){var b=document.createElement("div");b.obj=a;d.add(a,b);var e="file2 ";window.g_i_openfolder&&
(e+="file2_2 ");e+=a.styles;b.className=e;var j=e="";a.localpath_changed==true&&(j=" disable");e+='<div class="c0 icon '+a.file_icon+'"><div class="img"></div><i></i></div>';e+='<div class="c1">';e+='<div class="filename'+j+'"  data-action="task_openFolder2" >';e+='<div class="name">'+a.filename_name+" </div>";e+='<div class="suffix">'+a.filename_suf+"</div>";e+="</div>";e+='<div class="loading"><div class="bar" style="width:'+a.c_percent+'%;"></div></div>';e+='<div class="wording">'+a.wording+"</div>";
e+="</div>";e+='<div class="c2">';e+='<i class="seat"></i>';e+='<i class="pause" data-action="task_pause" title="\u6682\u505c"></i>';e+='<i class="resume" data-action="task_resume" title="\u542f\u52a8"></i>';e+='<i class="continue" data-action="task_continue" title="\u7eed\u4f20"></i>';e+='<i class="remove" data-action="task_remove" title="\u5220\u9664"></i>';e+='<i class="ok_upload"></i>';e+='<i class="ok_download"></i>';e+='<i class="go_folder'+j+'" data-action="task_openFolder" title="\u67e5\u770b"></i>';
e+="</div>";b.innerHTML=e;return b}function p(a,e){document.getElementById("box_list").classList.remove("overflow");a||(a=[]);for(var j=0;j<a.length;j++){var g=d.get(a[j]);g_remove_ease(g)}setTimeout(function(){var a=e.plist,j=e.clist;c(a.length);i(a.length+j.length);b(j.length)},350)}var l=200,o=document.getElementById("box_list"),m,q=document.getElementById("security_panel"),r=document.getElementById("security_appeal");q.onmouseover=function(){m&&clearTimeout(m)};q.onmouseout=function(a){q.contains(a.toElement)||
(m=setTimeout(h,200))};var s=false;return function(){var a={};a.renderBox=j;a.updateBox=g;a.renderBoxNum=c;a.clearBox=p;return a}()});define("modules/app.view",["./view/list","./view/box"],function(k,d){var c={};c.renderList=k.renderList;c.removeListRow=k.removeRow;c.setThumb=k.setThumb;c.updateRowDiv=k.updateRowDiv;c.renderBox=d.renderBox;c.updateBox=d.updateBox;c.addBoxRow=d.addBoxRow;c.updateBoxRow=d.updateBoxRow;c.renderBoxNum=d.renderBoxNum;c.clearBox=d.clearBox;return c});
define("common/db.ajax",[],function(){function k(){var b=a;if(typeof b==="undefined")return d();if(b!==-2){if(b===-1)return new XMLHttpRequest;b=f[b];if(typeof b==="string")return new ActiveXObject(b)}}function d(b){var e;try{if(b)throw 123;e=new XMLHttpRequest;a=-1}catch(g){for(var b=f,h=b.length,c=0;c<h;c++){try{e=new ActiveXObject(b[c]),a=c}catch(i){continue}break}}finally{return e||(a=-2),e}}function c(a){g++;e["xhr_"+g]=a;return g}function i(a){a="xhr_"+a;a in e&&(e[a]=null,delete e[a])}function b(b,
e,g,h,f){var m=k();try{m.open(h,b,true)}catch(q){a===-1&&(a=void 0,m=d(true),m.open(h,b,true))}var r=c(m),f=f||{},s=f.type||"json",u=f.timeout,b=f.timeout_ms,v;if(typeof u==="function"){if(!b||b<5E3)b=5E3;v=setTimeout(function(){clearTimeout(v);m.abort();i(r);m=null;u()})}m.onreadystatechange=function(){var a;m.readyState===4&&(v&&clearTimeout(v),m.status>=200&&m.status<300||m.status===304||m.status===1223||m.status===0?(a=s==="json"&&m.responseText?eval("("+m.responseText+")"):m.responseText)&&g(a):
g({ec:m.status}),i(r),m=null)};m.send(e);return r}var h={},f=["Msxml2.XMLHTTP.6.0","Msxml2.XMLHTTP.3.0","Msxml2.XMLHTTP","Microsoft.XMLHTTP"],a,g,e={};h.ajax=b;h.post=function(a,e,g,h){var f="",c;for(c in e)f+="&"+c+"="+encodeURIComponent(e[c]);return b(a,f,g,"POST",h)};h.get=function(a,e,g,h){var f=[],c;for(c in e)f.push(c+"="+encodeURIComponent(e[c]));a.indexOf("?")===-1&&(a+="?");a+=f.join("&");return b(a,null,g,"GET",h)};return h});
(function(k,d){typeof define==="function"&&define.amd?define("common/login",[],d):k.Login=d()})(this,function(){var k=function(){var c,b=top.external;if("CallHummerApi"in b){try{c=b.CallHummerApi("IM.GetClientKey"),c=JSON.parse(c)}catch(h){}if(c&&c.errorCode===0&&c.clientKey)return c.clientKey}if("Hummer_IM_GetClientKey"in b){try{c=b.Hummer_IM_GetClientKey(),c=JSON.parse(c)}catch(f){}if(c&&c.clientKey)return c.clientkey}},d=function(){var c=function(){function b(b){b=document.cookie.match(RegExp("(^| )"+
b+"=([^;]*)(;|$)"));return!b?"":decodeURIComponent(b[2])}return{get:b,uin:function(){var h=b("uin");return!h?null:parseInt(h.substring(1,h.length),10)}}}();return function(){var b;if(!(b=c.uin()))a:{var h;b=top.external;console.info(top.external);if("CallHummerApi"in b){try{h=b.CallHummerApi("Contact.GetSelfUin"),h=JSON.parse(h)}catch(f){}if(h&&h.errorCode===0&&h.uin){b=h.uin;break a}}b=void 0}return b}}(),c="http://"+window.location.hostname+"/clt_filetab/loginproxy.html";return{notLoginCallback:function(i){var b=
k(),h=d();if(b&&h){var f=i.loginproxy||c,a=document.createElement("iframe");a.onload=function(){i&&typeof i.succ=="function"&&i.succ();a.onload=null;document.body.removeChild(a);a=null};a.src="http://ptlogin2.qq.com/jump?clientuin="+h+"&clientkey="+b+"&u1="+encodeURIComponent(f);document.body.appendChild(a)}else console.error("clientkey && clientUin not defined! fallback with Login Box"),i&&typeof i.err=="function"&&i.err()}}});
define("common/cookie",[],function(){function k(d){d=document.cookie.match(RegExp("(^| )"+d+"=([^;]*)(;|$)"));return!d?"":decodeURIComponent(d[2])}return{get:k,del:function(d,c,i){document.cookie=d+"=; expires=Mon, 26 Jul 1997 05:00:00 GMT; path="+(i?i:"/")+"; "+(c?"domain="+c+";":"")},uin:function(){var d=k("uin");return!d?null:parseInt(d.substring(1,d.length),10)}}});
define("modules/cgi",["../common/db.ajax","../common/login","../common/cookie"],function(k,d,c){function i(g,f){if(!a||!a.isVisitor){o||(o=g.slice(0,10));var c=g.slice(0,10),d=g.slice(10);c.length&&(e&&clearTimeout(e),j&&clearTimeout(j),e=setTimeout(function(){a:{if(c.length==1){var e=c[0];if(l[e.filepath]){var j=l[e.filepath];if(new Date-j.t<18E4&&e.usedtimes<3){f(c,{ec:0,address_list:[j]});break a}}}for(var e=Math.floor((new Date).getTime()/1E3),g="",j=0;j<c.length;j++){j>0&&(g+=":");var d=c[j],
i=d.filepath,p=d.remotetype,k=d.filename;(d=d.fp)||(d=i.substr(4));d=(p==1?0:1)+"<"+d+"<"+escape(k);g+=d;c[j].thumbUrlLoading=true}h("http://pan.qun.qq.com/cgi-bin/thumbnail",{id:e,gc:a.groupid,fp_list:g},g_hitch(b,c,f))}},n));d&&d.length&&(j=setTimeout(function(){i(d,f)},p))}}function b(a,b,e){if(e.ec===0){if(!e.address_list)e.address_list=[];for(var j=0;j<e.address_list.length;j++){var g=a[j],f=e.address_list[j];f.t=new Date;if(g)g.usedtimes=0,l[g.filepath]=f}b(a,e)}}function h(b,e,j){var f=0,h=
setTimeout(function(){console.error("timeout!!!!!!");var a;a:{a={timeout_filelist:/filelist/g,timeout_permanent:/permanent/g,timeout_thumbnail:/thumbnail/g,timeout_delete:/delete/g};for(var e in a)if(a[e].test(b)){a=e;break a}a=void 0}g_log({type:"fail",msg:"CGI Timeout Error!"+b,report:a})},5E3),i=true,l,p=(new Date).getTime(),n=function(a){clearTimeout(h);var e=(new Date).getTime()-p;try{mm_report(b,a.ec,e)}catch(g){}a&&a.ec>=400&&a.ec<=600&&i&&(i=false,b&&b.indexOf("filelist")>0&&(a.ec>=400&&a.ec<
500&&g_report("cgi_filelist_4xx"),a.ec>=500&&a.ec<600&&g_report("cgi_filelist_5xx")));a&&(a.ec==1||a.ec==4)?(l=a,f++,f>1?t(a):(d.notLoginCallback({succ:o,err:t}),g_log({type:"fail",msg:"CGI NoLogin Error! Ec :"+a.ec,report:"ERR_CGI_NOT_LOGIN"}))):a&&j(a)},o=function(){if(f>1)t(l);else{for(var j=c.get("skey"),h=5381,d=0,i=j.length;d<i;++d)h+=(h<<5)+j.charCodeAt(d);g=h&2147483647;e.bkn=g;a.token=g;k.post(b,e,n)}},t=function(){l&&j(l);g_log({type:"error",msg:"\u81ea\u52a8\u7eed\u671f\u5931\u8d25! ",
report:"ERR_CGI_RELOGIN_FAILED"})};e.bkn=g;k.post(b,e,n)}var f={},a,g,e,j,n=60,p=300,l={},o;f.init=function(b){a=b;g=a.token};f.getList=function(b){h("http://pan.qun.qq.com/cgi-bin/filelist",{gc:a.groupid,s:0,n:250},b)};f.getAllList=function(b){h("http://pan.qun.qq.com/cgi-bin/filelist",{gc:a.groupid,s:0,n:2E4},b)};f.getThumb=i;f.deleteFile=function(b,e){var j=b.substr(4),g=b.substr(1,3);h("http://pan.qun.qq.com/cgi-bin/del_bat",{gc:a.groupid,fp1:j,bs1:g},e)};f.deleteFiles=function(b,e){var j=filepath.substr(4),
g=filepath.substr(1,3);h("http://pan.qun.qq.com/cgi-bin/del_bat",{gc:a.groupid,fp1:j,bs1:g},e)};f.permanent=function(b,e){h("http://pan.qun.qq.com/cgi-bin/permanent",{fp:b,gc:a.groupid},e)};f.renameFile=function(b,e,j){h("http://pan.qun.qq.com/cgi-bin/rename",{gc:a.groupid,fp:b.fp,fn:e,t:b.t==102?1:2},j)};f.checkFile=function(b,e,j){param={gc:a.groupid,bs:e,fp:b};h("http://pan.qun.qq.com/cgi-bin/checkAuditFlag",param,j)};return f});
define("modules/client_task",[],function(){var k={},d=top.external;k.getPlist=function(){var c={};if(window.external&&d.getTaskList){var i=d.getTaskList();typeof i!=="string"&&(i="");if(i==="")c.map={},c.status="busy";else if(i==="{}")c.map={},c.status="ok",c.empty=true;else{try{c.map=JSON.parse(i)}catch(b){console.error("\u5ba2\u6237\u7aef\u63a5\u53e3getTaskList\u8fd4\u56de\u7684\u6570\u636e\u6709\u95ee\u9898?parse\u51fa\u9519["+i+"]")}typeof c.map==="object"&&c.map!==null?c.status="ok":(c.map={},
c.status="parseerror")}}else console.log("task\u76f8\u5173\u63a5\u53e3\u4e0d\u5b58\u5728 getTaskList"),c={map:{},status:"ok",empty:true};return c};k.getClist=function(){var c={};if(window.external&&d.getCompleteTaskList){var i=d.getCompleteTaskList();typeof i!=="string"&&(i="");if(i==="")c.map={},c.status="busy";else if(i==="{}")c.map={},c.status="ok",c.empty=true;else{try{c.map=JSON.parse(i)}catch(b){console.error("\u5ba2\u6237\u7aef\u63a5\u53e3getCompleteTaskList\u8fd4\u56de\u7684\u6570\u636e\u6709\u95ee\u9898?parse\u51fa\u9519["+
i+"]")}typeof c.map==="object"&&c.map!==null?c.status="ok":(c.map={},c.status="parseerror")}}else console.log("task\u76f8\u5173\u63a5\u53e3\u4e0d\u5b58\u5728 getCompleteTaskList"),g_log("task\u63a5\u53e3\u4e0d\u5b58\u5728"),c={map:{},status:"ok",empty:true};return c};k.addUploadTask=function(c,i){var b;c||(c=1);window.g_flag_upload_temp&&(c=2);"addUploadTask"in d?b=d.addUploadTask(c,i):(console.log("task\u76f8\u5173\u63a5\u53e3\u4e0d\u5b58\u5728 addUploadTask"),g_log("task\u63a5\u53e3\u4e0d\u5b58\u5728"));
return b};k.addDownloadTask=function(c,i,b,h){window.external&&d.addDownloadTask?(b+="",c=d.addDownloadTask(c,i,b,h),console.debug("addDownLoadTask",c)):(console.log("task\u76f8\u5173\u63a5\u53e3\u4e0d\u5b58\u5728 addDownloadTask"),g_log("task\u63a5\u53e3\u4e0d\u5b58\u5728"),c=-1);return c};k.addDownloadFast=function(c,i,b){window.external&&d.downloadByXF?(b+="",c=d.downloadByXF(c,i,b),console.debug(c)):(console.log("task\u76f8\u5173\u63a5\u53e3\u4e0d\u5b58\u5728 downloadByXF"),g_log("task\u63a5\u53e3\u4e0d\u5b58\u5728"),
c=-1);return c};k.addContinueUploadTask=function(c,i,b,h){window.external&&d.addContinueUploadTask?c=d.addContinueUploadTask(c,i,b,h):(console.log("task\u76f8\u5173\u63a5\u53e3\u4e0d\u5b58\u5728 addContinueUploadTask"),g_log("task\u63a5\u53e3\u4e0d\u5b58\u5728"),c=-1);return c};k.removeTask=function(c){window.external&&d.removeTask?c=d.removeTask(c):(console.log("task\u76f8\u5173\u63a5\u53e3\u4e0d\u5b58\u5728 addContinueUploadTask"),g_log("task\u63a5\u53e3\u4e0d\u5b58\u5728"),c=-1);return c};k.removeCompleteTask=
function(c){window.external&&d.removeCompleteTask?c=d.removeCompleteTask(c):(g_log("task\u63a5\u53e3\u4e0d\u5b58\u5728"),c=-1);return c};k.pauseTask=function(c){window.external&&d.pauseTask?c=d.pauseTask(c):(console.log("task\u76f8\u5173\u63a5\u53e3\u4e0d\u5b58\u5728 addContinueUploadTask"),g_log("task\u63a5\u53e3\u4e0d\u5b58\u5728"),c=-1);return c};k.resumeTask=function(c){window.external&&d.resumeTask?c=d.resumeTask(c):(console.log("task\u76f8\u5173\u63a5\u53e3\u4e0d\u5b58\u5728 addContinueUploadTask"),
g_log("task\u63a5\u53e3\u4e0d\u5b58\u5728"),c=-1);return c};k.getTaskInfo=function(c){if(window.external&&d.getTaskInfo)var i=d.getTaskInfo(c);else console.log("task\u76f8\u5173\u63a5\u53e3\u4e0d\u5b58\u5728 getTaskInfo"),g_log("task\u63a5\u53e3\u4e0d\u5b58\u5728");return i};k.downloadFiles=function(c){window.external&&d.downloadFiles?(c=d.downloadFiles(JSON.stringify(c)),console.debug(c)):(console.log("task\u76f8\u5173\u63a5\u53e3\u4e0d\u5b58\u5728 downloadFiles"),g_log("task\u63a5\u53e3\u4e0d\u5b58\u5728"),
c=-1);return c};return k});define("modules/client",["./client_task","./client_hummer"],function(k,d){function c(){var b=k.getClist();if(b.map)for(var h in b.map){var f=b.map[h];f.id&&k.removeCompleteTask(f.id)===-1&&console.warn("\u79fb\u9664\u5b8c\u6210\u4efb\u52a1\u5931\u8d25\uff01")}}var i={};window.client=i;return function(){i.clearClist=c;for(var b in d)i[b]=d[b];for(b in k)i[b]=k[b];return i}()});
define("modules/getInfo",["../common/cookie","./client"],function(k,d){function c(){for(var b=k.get("skey"),a=5381,g=0,e=b.length;g<e;++g)a+=(a<<5)+b.charCodeAt(g);return a&2147483647}function i(b){b=window.location.hash.match(RegExp("(#|&)"+b+"=([^&]*)(&|$)"));return!b?"":decodeURIComponent(b[2])}function b(b){b=window.location.search.match(RegExp("(\\?|&)"+b+"=([^&]*)(&|$)"));return!b?"":decodeURIComponent(b[2])}var h;return function(){var f=k.uin(),a=i("gid")||b("guin"),g=function(){var b="refresh_"+
f+"_"+a;return k.get(b)*1?(k.del(b),true):false}();/^\d+$/.test(a)||(a=parseInt(a,10),isNaN(a)&&(a="0"));var e=(i("visitor")||b("visitor"))==="1",j={uin:f,groupid:a,isVisitor:e,nickName:d.GetNickName(f),token:c(),fromRefresh:g};Object.defineProperty(j,"nickName",{get:function(){return j.uins&&j.uins[f]?j.uins[f]:h?h:h=d.GetNickName(f)},set:function(){}});(i("debug")||b("debug"))==="1"&&(window.G_DEBUG=1);return j}});
define("modules/capacity",["../util/util"],function(k){var d,c;function i(){var g=d-c,e=d,j=g*100/e;g<0&&(g=0);var i=k.getFileSize(g)==="0B"?"0":k.getFileSize(g),e=k.getFileSize(e,{len:0}),p=i.replace(/^[0-9|\.|-|+]*/g,""),l=e.replace(/^[0-9|\.|-|+]*/g,"");p===l&&(j=i.replace(/[^0-9]*$/,"")*100/e.replace(/[^0-9]*$/,""));g>0&&j<1&&(j=1);j>1&&j<99&&(j=Math.round(j));j>99&&j<100&&(j=99);j>=100&&(j=100);p=j;j>0&&j<17&&(p=17);p>100&&(p=100);g=j;isNaN(j);j=i.replace(".","\u70b9");l=e.replace(".","\u70b9");
f.setAttribute("title","\u5df2\u4f7f\u7528"+g+"%");b.setAttribute("aria-label",j+"/"+l);h.style.width=p+"%";a.innerHTML=i+"/"+e}d=void 0;c=void 0;var b=document.getElementById("capacity"),h=document.getElementById("capacity_used"),f=document.getElementById("capacity_size_bar"),a=document.getElementById("capacity_info");return{init:function(a){a&&(d=a.capacity||a.capacitytotal,c=a.surplus_capacity||a.capacitytotal-a.capacityused||0,d||(c=d=2147483648),i())},releaseSpace:function(a){c+=a;i()},holdSpace:function(a){c-=
a;i()}}});
define("modules/cleanTask.parser",[],function(){function k(b){if(!b||!b.type||!b.status)return"";var j=f[b.type]+"-"+b.status;if(j in g)return j==="upload-uploadsecurityfail"&&a[b.securityattri]?a[b.securityattri]:g[j]}var d={ifError:function(a){return f[a.type]+"-"+a.status in g&&g?true:false}};d.getErrorWording=k;d.parseTask=function(a){var j=i[a.type];b[j]||console.warn("\u8bbe\u7f6ewording \u672a\u77e5\u4efb\u52a1\u7c7b\u578b=["+a.type+"]");b[j][a.status]||console.warn("\u8bbe\u7f6ewording \u672a\u77e5\u4efb\u52a1\u72b6\u6001=["+a.status+
"]");h[j][a.status]||console.warn("\u8bbe\u7f6e\u6837\u5f0f \u672a\u77e5\u4efb\u52a1\u72b6\u6001=["+a.status+"]");var g=b[j][a.status],f=h[j][a.status];if(f==="scan")a.c_percent&&(g+=a.c_percent+"%"),a.c_percent=0,f="pre";else if(f==="pre")a.c_percent=0;else if(f==="pause"||f==="continue")a.csize_str&&(g+=a.csize_str),a.filesize_str&&(g+=a.filesize_str);else if(f==="err")a.c_percent=0,a.status.indexOf("securityfail")>=0?(g="<i class='warn'></i>"+k(a),a.securityattri>=1&&a.securityattri<=5&&(g+="<i class='security'></i>")):
(a.errorcode==-1E3&&(g="\u8be5\u6587\u4ef6\u5df2\u88ab\u5220\u9664"),g="<i class='warn'></i>"+g);else if(f==="progress"){a.speed_str&&(g+=a.speed_str);var d;if(a.speed){d=Math.ceil((a.filesize-a.completesize)/a.speed);var o=Math.floor(d/3600),m=Math.floor(d%3600/60);d=Math.floor(d%60);o<10&&(o="0"+o);m<10&&(m="0"+m);d<10&&(d="0"+d);d="<span class='lefttime'>"+o+":"+m+":"+d+"</span>"}c[a.filepath]?new Date-c[a.filepath]>3E3&&d&&(g+=d):a.filepath&&(c[a.filepath]=new Date)}else f==="complete"?(a.c_percent=
100,g+=a.filesize_str):a.c_percent=0;a.wording=g;a.style_type=j;if(j==="continueupload")a.style_type="upload";a.style_status=f;a.styles=a.style_type+" "+a.style_status};var c={},i={upload:"upload",continueupload:"continueupload",download:"download"},b={upload:{scanning:"\u626b\u63cf\u4e2d...&nbsp;&nbsp;",scanfail:"\u626b\u63cf\u5931\u8d25&nbsp;&nbsp;",scanend:"\u626b\u63cf\u5b8c\u6210...&nbsp;&nbsp;",uploadgeturl:"\u51c6\u5907\u4e0a\u4f20...&nbsp;&nbsp;",uploadgeturlend:"\u4e0a\u4f20\u4e2d...&nbsp;&nbsp;",
uploadgeturlfail:"\u7533\u8bf7\u4e0a\u4f20\u5730\u5740\u5931\u8d25",uploadsecurityfail:"\u5b89\u5168\u626b\u63cf\u5931\u8d25",cancel:"\u7a7a\u95f4\u4e0d\u8db3,\u5df2\u53d6\u6d88\u4e0a\u4f20",uploadprogress:"\u4e0a\u4f20\u4e2d:&nbsp;&nbsp;",uploadfail:"\u4e0a\u4f20\u5931\u8d25",uploadcomplete:"\u4e0a\u4f20\u5b8c\u6210&nbsp;&nbsp;",pause:"\u6682\u505c&nbsp;&nbsp;","continue":"\u5f85\u7eed\u4f20&nbsp;&nbsp;"},download:{wait:"\u7b49\u5f85\u4e0b\u8f7d...&nbsp;&nbsp;",downloadready:"\u51c6\u5907\u4e0b\u8f7d...&nbsp;&nbsp;",
downloadgeturl:"\u51c6\u5907\u4e0b\u8f7d...&nbsp;&nbsp;",downloadgeturlfail:"\u83b7\u53d6\u4e0b\u8f7d\u5730\u5740\u5931\u8d25",cancel:"\u5df2\u53d6\u6d88\u4e0b\u8f7d&nbsp;&nbsp;",downloadgeturlend:"\u4e0b\u8f7d\u4e2d...",downloadprogress:"\u4e0b\u8f7d\u4e2d:&nbsp;&nbsp;",downloadfail:"\u4e0b\u8f7d\u5931\u8d25&nbsp;&nbsp;",downloadcomplete:"\u4e0b\u8f7d\u5b8c\u6210&nbsp;&nbsp;",pause:"\u6682\u505c&nbsp;&nbsp;"},continueupload:{scanning:"\u626b\u63cf\u4e2d...&nbsp;&nbsp;",scanfail:"\u626b\u63cf\u5931\u8d25&nbsp;&nbsp;",
scanend:"\u626b\u63cf\u5b8c\u6210...&nbsp;&nbsp;",uploadgeturl:"\u51c6\u5907\u7eed\u4f20...&nbsp;&nbsp;",uploadgeturlend:"\u7eed\u4f20\u4e2d...&nbsp;&nbsp;",uploadgeturlfail:"\u7533\u8bf7\u7eed\u4f20\u5730\u5740\u5931\u8d25",uploadsecurityfail:"\u5b89\u5168\u626b\u63cf\u5931\u8d25",cancel:"\u7a7a\u95f4\u4e0d\u8db3,\u5df2\u53d6\u6d88\u7eed\u4f20",uploadprogress:"\u7eed\u4f20\u4e2d:&nbsp;&nbsp;",uploadfail:"\u7eed\u4f20\u5931\u8d25",uploadcomplete:"\u7eed\u4f20\u5b8c\u6210&nbsp;&nbsp;",pause:"\u6682\u505c&nbsp;&nbsp;",
"continue":"\u5f85\u7eed\u4f20&nbsp;&nbsp;"}},h={upload:{scanning:"scan",scanfail:"err",scanend:"scan",uploadgeturl:"pre",uploadgeturlend:"pre",uploadgeturlfail:"err",uploadsecurityfail:"err",cancel:"err",uploadprogress:"progress",uploadfail:"err",uploadcomplete:"complete",pause:"pause","continue":"continue",remove:""},download:{wait:"pre",downloadready:"pre",downloadgeturl:"pre",downloadgeturlfail:"err",cancel:"err",downloadgeturlend:"pre",downloadprogress:"progress",downloadfail:"err",downloadcomplete:"complete",
pause:"pause"},continueupload:{scanning:"scan",scanfail:"err",scanend:"scan",uploadgeturl:"pre",uploadgeturlend:"pre",uploadgeturlfail:"err",uploadsecurityfail:"err",cancel:"err",uploadprogress:"progress",uploadfail:"err",uploadcomplete:"complete",pause:"pause","continue":"continue",remove:""}},f={upload:"upload",download:"download",continueupload:"upload"},a="\u5b89\u5168,\u626b\u63cf\u5230\u75c5\u6bd2\uff0c\u5df2\u53d6\u6d88\u4e0a\u4f20,\u626b\u63cf\u5230\u672a\u77e5\u98ce\u9669,\u626b\u63cf\u5230\u5b89\u5168\u98ce\u9669,\u626b\u63cf\u5230\u5b89\u5168\u98ce\u9669,\u626b\u63cf\u5230\u5b89\u5168\u98ce\u9669,\u6587\u4ef6\u5305\u542b\u654f\u611f\u8bcd".split(","),
g={"download-downloadgeturlfail":"\u4e0b\u8f7d\u5931\u8d25,\u8bf7\u7a0d\u5019\u518d\u8bd5","download-cancel":"","download-downloadfail":"\u4e0b\u8f7d\u5931\u8d25","upload-scanfail":"\u626b\u63cf\u5931\u8d25,\u8bf7\u7a0d\u5019\u518d\u8bd5","upload-uploadgeturlfail":"\u4e0a\u4f20\u5931\u8d25","upload-uploadsecurityfail":"\u4e0a\u4f20\u5b89\u5168\u626b\u63cf\u5931\u8d25","upload-cancel":"\u7a7a\u95f4\u4e0d\u8db3,\u5df2\u53d6\u6d88\u4e0a\u4f20","upload-uploadfail":"\u4e0a\u4f20\u5931\u8d25,\u8bf7\u7a0d\u5019\u518d\u8bd5"};
return d});
define("modules/cleanTask",["../util/util","./cleanTask.parser"],function(k,d){function c(b){if(!b.filename_esc)b.filename_esc=b.filename,b.filename=k.xssHtml(b.filename);b.speed_str="";b.wording="";b.csize_str="";b.updateFlag=true;var h=b.filename,f=b.filesize;b.speed_str=k.getFileSize(b.speed);b.speed_str===0?b.speed_str="":b.speed_str+="/S";if(b.filesize===void 0)b.filesize=b.completesize;b.filesize_str=k.getFileSize(f);b.csize_str=k.getFileSize(b.completesize);b.csize_str+="/";f=0;b.completesize>
0&&b.filesize>0&&(f=Math.round(b.completesize*100/b.filesize));b.c_percent=f;f=h.lastIndexOf(".");f>=0?(b.filename_name=h.substr(0,f),b.filename_suf=h.substr(f)):(b.filename_name=h,b.filename_suf="");b.file_icon=k.getFileIcon(b.filename_suf);d.parseTask(b);return[b]}function i(b){var h=[],f;for(f in b){var a=b[f];c(a);h.push(a)}return h}return function(){var b={};b.cleanItem=c;b.cleanMap=i;return b}()});
define("util/toast2",[],function(){var k,d,c;function i(){var a=f;if(a)a.style.opacity=0,a.style.display="none"}function b(a,b){var b=b||{},e=0;c&&clearTimeout(c);var j=b.parent||document.body,e=f?j!==h?2:0:1;switch(e){case 2:h.removeChild(f),h=f=void 0;case 1:f=document.createElement("div"),f.id="toast_box",f.className="toast_box",f.innerHTML="<div></div>",j.appendChild(f),h=j;case 0:if(!("autoHide"in b))b.autoHide=k;if(!("hasClose"in b))b.hasClose=d;var e=b,j=f,n=f.childNodes[0];j.style.left="0";
var p=j.style.opacity="";e.hasClose&&(p='<ul class="close_btn" tabindex="0" aria-label="'+a+',\u5173\u95ed" role="button"><li class="l"></li><li class="r"></li><li class="tri_masker"></li></ul>');n.className=e.show_fail_style?"fail":"succ";if(e.show_wait_style)n.className="wait";n.innerHTML=a+p;j.style.left="50%";j.style.marginLeft=-parseInt(getComputedStyle(j).width,10)/2-16+"px";j.style.marginTop=-parseInt(getComputedStyle(j).height,10)/2+"px";j.style.display="";e.autoHide&&(c=setTimeout(i,e.autoHide))}return f}
var h,f;k=1E3;d=false;c=void 0;return{show:b,yes:function(a){b(a)},no:function(a,g){g=g||{};g.show_fail_style=1;b(a,g)},wait:function(a,g){g=g||{};g.show_wait_style=1;g.autoHide=5E3;b(a,g)},hide:i}});
define("modules/handler/cgi/queryThumb",["../../cleanData","../../cleanTask","../../../util/toast2"],function(){function k(f){b=f}function d(f,a){if(window.g_flag_thumb_enable){if(!f)var g=document.getElementById("file_list").getBoundingClientRect().top,f=document.elementFromPoint(10,g+27+10);if(f&&f.classList.contains("file")){var e=f,g=a,j=document.getElementById("file_list").querySelectorAll(".file"),d=0;if(!g||g>h)g=h;for(var i=0;i<j.length;i++)if(j[i]==e){d=i;break}e=d-1;e<0&&(e=0);for(var d=
b.model.getListDataMap(),l=[],i=e;i<j.length&&i<e+20;i++){var k=j[i],k=k.id.substr(5);if((k=d[k])&&k.type_str=="\u56fe\u7247"&&!k.thumbUrl&&!k.thumbUrlLoading)if(l.push(k),l.length>=g)break}if(l.length>0&&l.length<g)for(;i<j.length;i++)if(k=j[i],k=k.id.substr(5),k=d[k],k.type_str=="\u56fe\u7247"&&!k.thumbUrl&&!k.thumbUrlLoading&&(l.push(k),l.length>=g))break;l.length&&c(l)}}}function c(f){var a=h;if(window.g_flag_thumb_enable){var g=b.cgi,e=f;f.length>a&&(e=f.splice(0,a));g.getThumb(e,i)}}function i(f,
a){if(a&&a.ec===0&&a.address_list){for(var g=0;g<a.address_list.length;g++)f[g].thumbUrl=a.address_list[g].url;b.view.setThumb(f)}}var b,h=10;return function(){var b={};b.do_query_thumb=c;b.do_fetch_thumb=d;return{init:k,tasks:b}}()});
define("modules/handler/cgi/getData",["../../cleanData","../../cleanTask","../../../util/toast2"],function(k,d,c){function i(a){e=a}function b(b){if(b&&b.ec==0)window.g_flag_cgiData_have=true;if(b&&b.ec!=600&&window.g_time_cgi_start)a.report1("flag1=7809&flag2=1&flag3=57","26="+(new Date-window.g_time_cgi_start)),window.g_time_cgi_start=null;var d=e.info,i=e.cgi,k=document.getElementById("app");if(b.ec!==0){if(b.ec===-10002)c.no("\u6e38\u5ba2\u6682\u65e0\u6743\u9650\u67e5\u770b\u7fa4\u5171\u4eab",
{autoHide:0}),k.style.display="none";g({type:"info",msg:"CGI filelist\u5931\u8d25 detail: uin["+d.uin+"]gin["+d.groupid+"]ec["+b.ec+"]"});g({type:"error",msg:"CGI filelist \u5931\u8d25 ec["+b.ec+"]",report:"ERR_CGI_GETSHARELIST"});j.classList.remove("open");window.g_flag_cgiData_have||c.no("\u62c9\u53d6\u5217\u8868\u5931\u8d25\uff0c\u8bf7\u7a0d\u540e<i class='reload' data-action='page_reload'>\u91cd\u8bd5</i>",{autoHide:0})}else if(b.ec==0&&b.role==0&&b.isPublic!=1)c.no("\u6e38\u5ba2\u65e0\u6743\u9650\u67e5\u770b\u975e\u516c\u5f00\u7fa4\u6587\u4ef6",
{autoHide:0}),k.style.display="none";else{if(b.ec==0&&b.flist==void 0)b.flist=[],b.name_list=[],b.capacitytotal=0;a.push("main","cgiReturn");d=h(b);d==0?f(b,4):d<3?f(b,2):d==3&&(f(b,3),i.getAllList(e.tasks.do_get_cgidata))}}function h(a){var b=e.local.cgiData,j;console.log("\u672c\u5730\u6709\u6570\u636e "+(b?b.n_all:0)+"-"+(b?b.flist.length:0)+" cgi\u6570\u636e"+a.n_all+"-"+a.flist.length);a&&a.flist&&a.flist.length<=250&&a.flist.sort(function(a,b){return b.ut-a.ut});if(b){for(var g in b)a[g]===
void 0&&(a[g]=b[g]);if(a.n_all==a.flist.length)if(b.n_all==a.n_all&&b.flist.length==a.flist.length){if(b.n_all==0||b.n_all>0&&b.flist[0].fp==a.flist[0].fp)j=0}else j=-1;else if(b.n_all==a.n_all&&b.n_all==b.flist.length||b.n_all==0||b.n_all>0&&b.flist[0].ut==a.flist[0].ut){console.log("\u90e8\u5206\u6570\u636e \u4e0e\u672c\u5730\u6570\u636e\u76f8\u540c");j=0;for(g=a.flist.length;g<a.n_all;g++){var f=b.flist[g];f&&a.flist.push(f)}var h={};a.name_list?a.name_list.forEach(function(a){h[a.u]=a.n}):a.name_list=
[];b.name_list&&b.name_list.forEach(function(b){h[b.u]||a.name_list.push(b)})}else console.log("\u9700\u8981\u5168\u91cf\u62c9\u53d6"),j=3}else j=a.n_all>a.flist.length?3:-2;e.local.cgi.set(a);return j}function f(a,b){var g=document.getElementById("app"),f=e.model,h=e.view,i=e.capacity,s=e.info,u=a.role;if(a.isPublic===0&&u===1)c.no("\u6e38\u5ba2\u65e0\u6743\u9650\u67e5\u770b\u975e\u516c\u5f00\u7fa4\u6587\u4ef6",{autoHide:0}),g.style.display="none";else{s=k.cleanArray(a,s);s.isVisitor?(g.classList.add("visitor"),
e.isVisitor=true):(e.isVisitor=false,g.classList.remove("visitor"));for(var g=s.listData,u=s.boxData,v=s.imgData,z=0;z<u.length;z++)d.cleanItem(u[z]);j.classList.remove("open");f.setListData(g);a.n_all>a.flist.length?h.renderList(g,null,a.n_all):b!=5&&h.renderList(g);s.isVisitor||(b>=2&&(f.setContinueTask(u),h.renderBox(f.getBoxData(),true),n||(n=true,e.tasks.do_query_thumb(v))),console.log("\u521d\u59cb\u5316\u5bb9\u91cf"),console.log(a),a.capacitytotal!==void 0&&i.init(a))}}var a=window.TRecord,
g=window.g_log,e,j=document.getElementById("loader"),n=false;return function(){var a={};a.do_get_cgidata=b;a.do_get_data=f;return{init:i,tasks:a}}()});
define("modules/handler/client/onMsg",["../../cleanTask"],function(k){function d(b){c=b}var c,i=top;if(typeof i.onClientEvent!=="function")return window.addEventListener("message",function(b){var h;try{typeof b.data==="string"&&(h=JSON.parse(b.data))}catch(f){}if(h&&typeof h==="object")if(h.from==="Client")switch(b=h.data,typeof b==="string"&&(b=JSON.parse(h.data)||{}),h=b.cmd||"",h){case "OnFiletransporterEvent":b=b.param;typeof b!=="object"?console.error("onFiletransporterEvent param parse error"):
(h=b.event,b=b.task,k.cleanItem(b),(h=c.tasks["do_msg_"+{newtask:"newtask",taskcomplete:"taskcomplete",taskpause:"taskpause",taskresume:"taskresume",startprogress:"taskprogress",taskabort:"taskabort"}[h]])&&h(b));break;case "OnGroupShareTabChangedEvent":break;default:console.warn("warn:\u9884\u671f\u5916\u7684message.cmd:"+h)}else if(h.from==="jubao")switch(h=h.cmd||"",h){case "jubao_close":c.tasks.do_jubao_close();break;default:console.warn("warn:\u9884\u671f\u5916\u7684message.cmd:"+h)}}),i.PostMessage=
i.onClientEvent=function(b){var h;console.debug(b);if(b){if(typeof b==="string")try{h=JSON.parse(b)}catch(f){console.error("[Client|init()]msg is string, but parse to object catch e!")}typeof h!=="object"?console.error("[Client|init()]after parse, got no object!"):window.postMessage(b,"*")}else console.error("[Client] msg is not exist!")},{init:d,tasks:{}}});
define("modules/handler/client/newTask",[],function(){function k(b){c=b}function d(b){var h=c.model,f=c.view;b.task_starttime=parseInt((new Date).getTime()/1E3,10);var a=h.addNewTask(b);f.updateBox([a],h.getBoxData());document.getElementById("box_list");b.type=="download"&&c.tasks.do_file_downloading(document.getElementById("list_"+b.filepath));g_report(i[b.type]);c.tasks.do_box_refresh()}var c,i={upload:386381,continueupload:386382,download:386383};return function(){var b={};b.do_msg_newtask=d;return{init:k,
tasks:b}}()});
define("modules/handler/client/taskProgress",[],function(){function k(d){c=d}function d(d){var b=c.model,h=c.view,f=c.capacity;d.createtime=parseInt((new Date).getTime()/1E3,10);var a=b.updatePlistItem(d);d.status==="uploadprogress"&&setTimeout(function(){c.tasks.do_box_open()},10);h.updateBox([a],b.getBoxData());d.remotetype===1&&f.holdSpace(d.filesize);d.type=="download"&&c.tasks.do_file_downloading(document.getElementById("list_"+d.filepath))}var c;return function(){var c={};c.do_msg_taskprogress=d;
return{init:k,tasks:c}}()});define("modules/task2File",["../util/util","./cleanData"],function(k,d){return function(c,i){var b={},h;for(h in c)b[h]=c[h];if(b){h=b.filepath.substr(1,3);var f=parseInt((new Date).getTime()/1E3,10);b.filepath=b.filepath;b.fp=b.filepath.substr(4);if(c.localname)b._localpath=b.localname;b.uploaduin=i.uin;b.busid=h;b.ttl=864E3;b.createtime=f;b.updatetime=f;b.downloadtimes=0;b.uploadnick=i.nickName;b.uploadsize=b.filesize;d.cleanItem(b,i,true);return b}else console.error("task is null")}});
define("modules/handler/client/taskComplete",["../../task2File"],function(k){function d(f){b=f}function c(f){console.debug("taskcomplete",f);i(h[f.type]);var a=b.model,g=b.view,e=b.info,j=b.client,c=b.local,d=a.updatePlistItem(f);g.updateBox([d],a.getBoxData());j.clearClist();j=f.localpath;j.indexOf("OSRoot:\\")!=0&&(j="OSRoot:\\"+j);c.lp.add(f.filepath.substr(4),j);e=k(d,e);e.is_success=true;e.style_issucc="succ";c=a.getListDataMap();if(d=c[e.filepath])d._localpath=j;if(f.type.indexOf("upload")>=
0)a=a.addListData(e),d=c[e.filepath],d._localpath=j,g.renderList(a),e.type_str=="\u56fe\u7247"&&b.tasks.do_query_thumb([e]),i("UPLOAD_SUCC");else if(f.type.indexOf("download")>=0){var l=document.getElementById("list_"+e.filepath);if(!l)a=a.addListData(e),d=c[e.filepath],d._localpath=j,g.renderList(a),l=document.getElementById("list_"+e.filepath);l?(l.classList.add("succ"),window.g_i_openfolder&&b.tasks.do_file_downloadsucc(l)):console.error("download \u6210\u529f\u6253\u52fe\u5f02\u5e38"+e.filepath);
if(d)d.inDownload=false,d.dt++,d.downloadtimes++,b.view.updateRowDiv(l,d);i("DOWNLOAD_BTN_CLICK#SUCC")}b.tasks.do_batch_download_check(f)}var i=window.g_report,b,h={upload:386384,continueupload:386385,download:386386};return function(){var b={};b.do_msg_taskcomplete=c;return{init:d,tasks:b}}()});
define("modules/handler/client/taskAbort",[],function(){function k(a){h=a}function d(a){var g=h.model,e=h.view,j=g.updatePlistItem(a);e.updateBox([j],g.getBoxData());g=f[a.type];e=g[a.status];if(!e)e=g._default,i({type:"error",msg:"\u5ba2\u6237\u7aef\u4efb\u52a1\u5931\u8d25_"+a.type+"_"+a.status});b(e);if(a.errorcode||a.securityattri)if(g=a.errorcode,e=c("\u4efb\u52a1\u5931\u8d25",a),i({type:"info",msg:a.type+"\u4efb\u52a1\u5931\u8d25"+e}),g===32221991){a=h.client;g=c("\u4efb\u52a1\u5931\u8d25",j);
j.retry_times?j.retry_times++:j.retry_times=1;j.retry_times>3?i({type:"info",msg:"\u4efb\u52a1\u91cd\u8bd5\u6b21\u6570\u8d85\u8fc73\u6b21"+g,report:"ERR_TASK_RETRY_REACH_MAX"}):(i({type:"info",msg:"\u4efb\u52a1\u91cd\u8bd5"+g,report:"ERR_TASK_RETRY"}),a.addContinueUploadTask(j.filepath,j.localpath,j.filename_esc||j.filename,j.remotetype));b("ERR_FTN_32221991");return}else g===12029&&b("ERR_FTN_12029");h.tasks.do_file_downloadback(document.getElementById("list_"+a.filepath));h.tasks.do_batch_download_check(a)}
function c(a,b){var e=a,j=h.info;e+="gin["+j.groupId+"]";e+="uin["+j.uin+"]";e+="fn["+b.filename+"]";e+="fp["+b.filepath+"]";e+="st["+b.status+"]";e+="ec["+b.errorcode+"]";e+="sa["+b.securityattri+"]";e+="id["+b.id+"]";return e}var i=window.g_log,b=window.g_report,h,f={upload:{cancel:386303,remove:386305,scanfail:38306,uploadsecurityfail:386307,uploadgeturlfail:386308,uploadfail:386309,_default:386310},continueupload:{cancel:386319,remove:386320,scanfail:386321,uploadsecurityfail:386322,uploadgeturlfail:386323,
uploadfail:386324,_default:386325},download:{cancel:386328,remove:386329,downloadgeturlfail:386330,downloadfail:386331,_default:386332}};return function(){var a={};a.do_msg_taskabort=d;return{init:k,tasks:a}}()});define("modules/handler/client/taskPause",[],function(){function k(d){c=d}function d(d){var b=c.model,h=c.view,f=b.updatePlistItem(d);h.updateBox([f],b.getBoxData());c.tasks.do_batch_download_check(d)}var c;return function(){var c={};c.do_msg_taskpause=d;return{init:k,tasks:c}}()});
define("modules/handler/client/taskResume",[],function(){function k(d){c=d}function d(d){var b=c.model,h=c.view,d=b.updatePlistItem(d);h.updateBox([d],b.getBoxData())}var c;return function(){var c={};c.do_msg_taskresume=d;return{init:k,tasks:c}}()});
define("modules/handler/box/init",["../../cleanTask","../../task2File"],function(k,d){function c(c){b=c}function i(){var c=b.client,f=b.view,a=b.model,g=b.local,e=c.getPlist(),j=c.getClist(),e=k.cleanMap(e.map),j=k.cleanMap(j.map);c.clearClist();(c=g.clistData)||(c=[]);for(var i=0;i<j.length;i++){var p=j[i];if(!(p.status.indexOf("complete")<0)){var l=d(p,b.info),o=l.localpath;o.indexOf("OSRoot:\\")!=0&&(o="OSRoot:\\"+o);l._localpath=o;l.fp=l.filepath.substr(4);b.local.lp.add(l.fp,o);c.unshift(p)}}g.clist.set(c);
e.sort(function(a,b){return b.id-a.id});e&&e.length&&(a.setPlist(e),setTimeout(function(){b.tasks.do_box_open()},500));c&&c.length&&a.setClist(c);(a=a.getBoxData())&&f.renderBox(a,true)}var b;return function(){var b={};b.do_box_init=i;return{init:c,tasks:b}}()});define("modules/handler/box/pause",[],function(){function k(b){i=b}function d(b){i.client.pauseTask(b.parentNode.parentNode.obj.id);c("PAUSE_BTN_CLICK")}var c=window.g_report,i;return function(){var b={};b.do_task_pause=d;return{init:k,tasks:b}}()});
define("modules/handler/box/resume",[],function(){function k(b){i=b}function d(b){var d=i.client,f=i.tasks.do_box_open,b=b.parentNode.parentNode.obj.id;f();d=d.resumeTask(b);console.warn("\u6267\u884cresume\u7684\u8fd4\u56de\u7801=["+d+"]");c("RESUME_BTN_CLICK")}var c=window.g_report,i;return function(){var b={};b.do_task_resume=d;return{init:k,tasks:b}}()});
define("modules/handler/box/continue",[],function(){function k(b){i=b}function d(b){b=b.parentNode.parentNode.obj;i.client.addContinueUploadTask(b.filepath,b.localname,b.filename_esc||b.filename,b.remotetype);c("CONTINUEUPLOAD_BTN_CLICK")}var c=window.g_report,i;return function(){var b={};b.do_task_continue=d;return{init:k,tasks:b}}()});
define("modules/handler/box/remove",[],function(){function k(b){i=b}function d(b){var d=i.client,f=i.model,a=i.view,g=i.cgi,b=b.parentNode.parentNode,e=b.obj,j=e.type,k=e.filepath,p=true;e.id&&(d.removeTask(e.id),p=true);p&&(e.id&&f.removePlistItem(e.id),f.removePlistItem(e.filepath),delete window.g_plistMap[e.filepath],j&&j.indexOf("upload")>=0&&k&&g.deleteFile(k,function(a){if(a.ec==void 0)a.ec=a.code;a.ec!==0&&(console.warn("\u672a\u80fd\u6210\u529f\u5220\u9664\u8fdc\u7a0b\u670d\u52a1\u5668\u4e0a\u7684\u6587\u4ef6!"),
g_log({type:"error",msg:"\u5220\u9664\u8fdc\u7a0b\u6587\u4ef6\u5931\u8d25fp["+k+"]ec["+a.ec+"]",report:"ERR_CGI_DELETE"}))}),a.updateBox([],f.getBoxData()),d.clearClist(),g_remove_ease(b));c("CANCEL_BTN_CLICK");i.tasks.do_file_downloadback(document.getElementById("list_"+e.filepath));i.tasks.do_batch_download_check(e)}var c=window.g_report,i;return function(){var b={};b.do_task_remove=d;return{init:k,tasks:b}}()});
define("modules/handler/box/boxToggle",["../../cleanTask"],function(k){function d(a){g=a}function c(){document.getElementById("box");n?b():(i(),a("BOX_ENTRY_SHOWCLICK"))}function i(){var a=g.view,b=g.model;if(n)e&&clearTimeout(e),e=setTimeout(f,0);else{var j=document.getElementById("box");document.getElementById("box_list");j.classList.add("open");a.renderBox(b.getBoxData());e&&clearTimeout(e);e=setTimeout(f,0);n=true}}function b(){n=false;var a=document.getElementById("box");document.getElementById("box_list");
a.classList.remove("open");e&&(clearTimeout(e),e=null)}function h(){e||(e=setTimeout(f,j))}function f(){var a=g.view,b=g.model,c=g.client.getPlist(),d=false;if(c.empty&&c.status==="ok")e&&clearTimeout(e),e=null;else if(c.status==="busy")e=setTimeout(f,j);else{for(var h=/progress|ready|scan|geturl/ig,c=k.cleanMap(c.map),i=0;i<c.length;i++){var n=c[i];n.type=="download"&&(n.state=="canceled"?g.tasks.do_file_downloadback(document.getElementById("list_"+n.filepath)):g.tasks.do_file_downloading(document.getElementById("list_"+
n.filepath)));h.test(n.status)&&(d=true)}h=b.updatePlist(c);a.updateBox(h,b.getBoxData());d&&(e=setTimeout(f,j))}}var a=window.g_report,g,e,j=299,n=false;return function(){var a={};a.do_box_toggle=c;a.do_box_open=i;a.do_box_close=b;a.do_box_refresh=f;a.do_start_refresh=h;return{init:d,tasks:a}}()});
define("modules/handler/box/clearHistory",[],function(){function k(d){c=d}function d(){var d=c.local,b=c.client,h=c.model,f=c.view,a=h.clearClist();f.clearBox(a,h.getBoxData());b.clearClist();d.clist.clear()}var c;return function(){var c={};c.do_clear_history=d;return{init:k,tasks:c}}()});
define("modules/handler/box/openFolder",[],function(){function k(b){a=b}function d(a){if(window.external&&window.external.isFileExist){var b=window.external.isFileExist(a);if(b=="false"||b===false)return client.alert("\u6b64\u6587\u4ef6\u5939\u4e0d\u5b58\u5728\uff0c\u53ef\u80fd\u88ab\u5220\u9664\u6216\u88ab\u79fb\u52a8\u5230\u5176\u4ed6\u4f4d\u7f6e"),false}if(window.external&&window.external.openFile)if(b=window.external.openFile(a),b=="success")return true;else if(b!=="file cannot open")return false;
if(window.external&&window.external.openFolder&&(b=window.external.openFolder(a),b!="success"))return client.alert("\u6b64\u6587\u4ef6\u5939\u4e0d\u5b58\u5728\uff0c\u53ef\u80fd\u88ab\u5220\u9664\u6216\u88ab\u79fb\u52a8\u5230\u5176\u4ed6\u4f4d\u7f6e"),false}function c(b){var e=a.model,b=b.parentNode.parentNode.parentNode,j=b.id.substr(5),e=e.getListDataMap()[j];console.log("do_open_folder3 --------------- start");console.log(e);console.log("do_open_folder3 --------------- end");if(e)(j=e._localpath)?
(j.indexOf("OSRoot:\\")!=0&&(j="OSRoot:\\"+j),d(j,e)==false&&i(b,e)):i(b,e);f("open_folder_from_list")}function i(b,e){var j=a.local;e._localpath=null;j.lp.remove(e.fp);b&&a.tasks.do_file_downloadback(b)}function b(b){var e=b.parentNode.parentNode,j=e.obj;console.log("open folder ----------------------- start");console.log(j);console.log("open folder ----------------------- end");var c=j._localpath||j.localpath||j.localname;c&&c.indexOf("OSRoot:\\")!=0&&(c="OSRoot:\\"+c);if(d(c,j)==false){var h=e.querySelector(".filename"),
e=e.querySelector(".go_folder");b.classList.add("disable");h.classList.add("disable");e.classList.add("disable");j.localpath_changed=true;a.local.clist.set(a.local.clistData);if((b=a.model.getListDataMap()[j.filepath])&&b._localpath==c)(e=document.getElementById("list_"+b.filepath))&&i(e,b)}j&&j.type&&j.type.indexOf("upload")>=0?f("open_folder_upload"):j&&j.type&&j.type.indexOf("download")>=0&&f("open_folder_download")}function h(a){b(a)}var f=window.g_report,a;return function(){var a={};a.do_task_openFolder=
b;a.do_task_openFolder2=h;a.do_open_folder3=c;return{init:k,tasks:a}}()});define("modules/handler/file/upload",[],function(){function k(b){i=b}function d(){i.client.addUploadTask();c("UPLOAD_BTN_CLICK")}var c=window.g_report,i;return function(){var b={};b.do_file_upload=d;return{init:k,tasks:b}}()});
define("modules/handler/file/delete",["../../../util/toast2"],function(k){function d(a){g=a}function c(a){for(var b=g.cgi,c=0;c<a.length;c++)b.deleteFile(a[c].filepath)}function i(){var a=g.model,j=g.cgi,c=g.client,d=g.lastActiveRow,i=g.tasks.do_hide_menu;i();if(d&&(a=a.getListDataMap()[d.id.substr(5)])){var i=a.filepath,k=a.remotetype,m=a.filesize;c.confirm("\u4f60\u786e\u5b9a\u8981\u5220\u9664\u6587\u4ef6 "+a.filename_esc+" \u5417?")&&j.deleteFile(i,f(b,a.filepath,k,m,d))}h("DELETE_BTN_CLICK")}
function b(b,j,c,d,f){var i=g.model,d=g.view,m=g.client,q=g.capacity;console.warn("do delete result:",b);if(f&&f.ec===void 0)f.ec=f.code;f.ec===0?(k.show("\u5220\u9664\u6210\u529f"),f=i.removeListData(b),d.removeListRow(b,f),j===1&&q.releaseSpace(c),g.local.cgi.remove(b.substr(4)),h("DELETE_BTN_CLICK#SUCC")):(m.alert("\u5220\u9664\u5931\u8d25"),a({type:"error",msg:"\u5220\u9664\u5931\u8d25fp["+b+"]ec["+f.ec+"]",report:"ERR_CGI_DELETE"}))}var h=window.g_report,f=window.g_hitch,a=window.g_log,g;return function(){var a=
{};a.do_file_delete=i;a.do_deleteAll=c;return{init:d,tasks:a}}()});
define("modules/handler/file/preview",["../../../util/toast2"],function(k){function d(b){a=b}function c(c){b(c);a.tasks.do_file_active(c);g_report("preview_click_filename")}function i(c){for(c=c.parentNode.parentNode;!c.classList.contains("file");)c=c.parentNode;b(c);a.tasks.do_file_active(c);g_report("preview_click_img")}function b(b){var e=a.tasks.do_hide_menu,c=a.model,d=a.cgi;e();if(b&&(b=c.getListDataMap()[b.id.substr(5)])){var e=b.filepath,c=b.filename,h=b.filesize;if(b.type_str==="\u56fe\u7247")h>
20971520?client.alert("\u56fe\u7247\u592a\u5927\u4e0d\u652f\u6301\u9884\u89c8\uff0c\u8bf7\u76f4\u63a5\u4e0b\u8f7d"):(b.usedtimes=b.usedtimes>=0?b.usedtimes+1:1,console.log("\u56fe\u7247\u52a0\u8f7d usedtimes:"+b.usedtimes),k.wait("\u6b63\u5728\u52a0\u8f7d\u9884\u89c8\u56fe\u2026"),console.log("preview toast"),window.onblur=function(){console.log("blur");window.onblur=null;k.hide()},console.log("cgi.getFilepath"),d.getThumb([b],f));else try{console.debug(e,c),window.external&&window.external.previewFile(e,
c)}catch(i){}}}function h(){b(a.lastActiveRow);g_report("preview_click_menu")}function f(b,e){console.log("get FilePath Back");console.log(e);if(e.ec===0){var c=e.address_list[0].url;console.debug(c);a.client.preview(c)}else console.log("\u83b7\u53d6\u7f29\u7565\u56fe\u5931\u8d25"+b[0].filename)}var a;return function(){var a={};a.do_file_preview=h;a.do_img_preview=i;a.do_preview_filename=c;return{init:d,tasks:a}}()});
define("modules/handler/file/rename",["../../../util/util","../../../util/toast2"],function(k,d){function c(a){l=a;m.onkeydown=b;m.onpaste=i}function i(a){var b="";a.clipboardData&&(b=a.clipboardData.getData("Text"));/[\\\/\*\:\"<>\|\?]/.test(b)?(q.innerHTML=r,setTimeout(function(){q.innerHTML=""},3E3),a.preventDefault()):q.innerHTML=""}function b(a){var b=a.keyCode,e=[56,186,222,188,190];[220,191].indexOf(b)>=0||a.shiftKey&&e.indexOf(b)>=0?(q.innerHTML=r,setTimeout(function(){q.innerHTML=""},3E3),
a.preventDefault()):b==13?f():b==65&&a.ctrlKey==true?p(m,0,m.value.length):q.innerHTML=""}function h(a){l.state_inRename=true;n(a);g_report("menu_file_rename")}function f(){var b=m.value;console.log(b);if(b.length==0||b.replace(/\s/g,"").length==0)q.innerHTML="\u5fc5\u987b\u952e\u5165\u6587\u4ef6\u540d",setTimeout(function(){q.innerHTML=""},3E3);else{var e=l.cgi,c=l.lastActiveRow;console.log(c);var j=l.model.getListDataMap();j&&c&&c.id&&(c=j[c.id.substr(5)])&&e.renameFile(c,b+c.filename_suf,g_hitch(a,
c,b));g_report("btn_rename_ok")}}function a(a,b,e){if(e.ec===0){console.log("rename succ");console.log(a);a.fn=k.xssHtml(b+a.filename_suf);a.filename=a.fn;a.filename_esc=b+a.filename_suf;a.filename_name=k.xssHtml(b);e=document.getElementById("list_"+a.filepath);g();d.yes("\u91cd\u547d\u540d\u6210\u529f");if(e){var e=e.childNodes[2].childNodes[0],c=a.filename_esc;a.type_str=="\u56fe\u7247"&&(c="\u9884\u89c8\u56fe\u7247 : "+c);e.setAttribute("title",c);e.childNodes[0].innerHTML=k.xssHtml(b)}l.local.cgi.update(a)}else(a=
s[e.ec])?q.innerHTML=a:(g(),d.no(u))}function g(){var a=l.lastOpenMenu;a&&a.classList.remove("open");l.lastOpenMenu=null}function e(){g()}function j(){g()}function n(){var a=l.model,b=l.lastActiveRow;q.innerHTML="";console.log(b);if(b)l.tasks.do_file_active(b),a=a.getListDataMap()[b.id.substr(5)].filename_esc,b=a.lastIndexOf("."),b>=0&&(a=a.substr(0,b)),o.classList.add("open"),m.value=a,setTimeout(function(){p(m,0,m.value.length);m.select();l.lastOpenMenu&&l.lastOpenMenu!=o&&l.lastOpenMenu.classList.remove("open");
l.lastOpenMenu=o},10)}function p(a,b,e){if(a.createTextRange){var c=a.createTextRange();c.collapse(true);c.moveStart("character",b);c.moveEnd("character",e);c.select()}else if(a.setSelectionRange)a.setSelectionRange(b,e);else if(a.selectionStart)a.selectionStart=b,a.selectionEnd=e;a.focus()}var l,o=document.getElementById("rename_panel"),m=document.getElementById("new_name"),q=document.getElementById("rename_err_text"),r='\u6587\u4ef6\u540d\u4e2d\u4e0d\u5141\u8bb8\u5305\u62ec \\ / : * ? " &lt; &gt; |',
s={2:"\u7cfb\u7edf\u5185\u90e8\u9519\u8bef",3:"\u8f93\u5165\u53c2\u6570\u9519\u8bef",11:"\u6587\u4ef6\u540d\u5305\u542b\u975e\u6cd5\u5b57\u7b26( / : * \uff1f\u201c < > |)",12:"\u6587\u4ef6\u540d\u957f\u5ea6\u9650\u5236(\u4e2d\u6587\u6216\u8005\u82f1\u6587\u957f\u5ea6\u90fd\u9650\u5236\u4e3a127)",13:"\u6587\u4ef6\u540d\u5305\u542b\u654f\u611f\u8bcd\u6c47",14:"\u767b\u5f55\u6001\u6821\u9a8c\u5931\u8d25",15:"\u6210\u5458\u5173\u7cfb\u6821\u9a8c\u5931\u8d25",16:"\u83b7\u53d6\u6587\u4ef6\u4fe1\u606f\u5931\u8d25",
17:"ftn\u8fd4\u56de\u6587\u4ef6\u4e0d\u5b58\u5728",18:"\u5373\u901a\u5b89\u5168\u4e2d\u5fc3\u68c0\u6d4b\u5931\u8d25"},s={12:"\u6587\u4ef6\u540d\u8fc7\u957f,\u8bf7\u91cd\u65b0\u4fee\u6539\u6587\u4ef6\u540d",13:"\u6587\u4ef6\u540d\u79f0\u4e2d\u5305\u542b\u654f\u611f\u8bcd\uff0c\u8bf7\u91cd\u65b0\u4fee\u6539\u6587\u4ef6\u540d",17:"\u6587\u4ef6\u5df2\u88ab\u5220\u9664,\u8bf7\u5237\u65b0\u9875\u9762"},u="\u7f51\u7edc\u5f02\u5e38\uff0c\u91cd\u547d\u540d\u5931\u8d25\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5",
u="\u91cd\u547d\u540d\u5931\u8d25\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5";return function(){var a={};a.do_file_rename=h;a.do_rename_ok=f;a.do_rename_cancel=j;a.do_rename_close=e;return{init:c,tasks:a}}()});
define("modules/handler/file/download",[],function(){function k(a){e=a}function d(){var a=e.lastActiveRow,b=e.client,c=e.model.getListDataMap()[a.id.substr(5)];c?c.inDownload?setTimeout(function(){e.tasks.do_box_open()},10):b.addDownloadFast(c.filepath,c.filename_esc,c.filesize):console.error("model\u7684datamap\u91cc\u6ca1\u6709\u8be5\u6570\u636e"+a.id);e.tasks.do_hide_menu(true);g("downloadfast_btn_click")}function c(){var a=e.lastActiveRow,b=e.client,c=e.model,d=c.getListDataMap()[a.id.substr(5)];
if(d)if(d.inDownload)setTimeout(function(){e.tasks.do_box_open()},10);else{var f=d.filepath,h=d.filename_esc,i=d.filesize;d.fp=d.fp.replace("/myrecv","");e.cgi.checkFile(d.fp,d.t||d.busid,function(a){a.ec===0&&a.audit===3?(b.alert("\u8be5\u6587\u4ef6\u56e0\u591a\u6b21\u88ab\u4e3e\u62a5\u4e3a\u8272\u60c5\u6587\u4ef6\uff0c\u5df2\u88ab\u5220\u9664"),a=c.removeListData(f),view.removeListRow(f,a)):a.ec===0&&b.addDownloadTask(f,h,i)})}else console.error("model\u7684datamap\u91cc\u6ca1\u6709\u8be5\u6570\u636e"+
a.id);e.tasks.do_hide_menu(true);g("SAVEAS_BTN_CLICK")}function i(a,b){var c=document.createElement("div");c.innerHTML='<div class="img"></div>';if(typeof a!=="undefined"){var d=e.model.getListDataMap()[a.id.substr(5)];if(d)c.className="file_animate "+d.file_icon,d=b.getBoundingClientRect(),c.style.right=window.innerWidth-d.left+"px",c.style.top=d.top-20+"px",document.body.appendChild(c),setTimeout(function(){document.body.removeChild(c)},1500)}else c.className="file_animate filedef",c.style.right=
window.innerWidth/2+"px",c.style.top=window.innerHeight/2+"px",document.body.appendChild(c),setTimeout(function(){document.body.removeChild(c)},1500)}function b(a){if(a){var b=a.querySelector(".btn_left");if(b&&!b.classList.contains("downloading"))new Date-a.clickTime<1E3&&i(a,b),b.classList.remove("download"),b.classList.remove("chakan"),b.classList.add("disable"),b.classList.add("downloading"),b.nextSibling.classList.add("disable"),b.innerHTML="&nbsp;\u4e0b\u8f7d\u4e2d",b.setAttribute("title","\u4e0b\u8f7d\u4e2d")}}
function h(a){if(a){a.classList.add("succ");var b=a.querySelector(".btn_left");b&&setTimeout(function(){b.classList.remove("download");b.classList.remove("downloading");b.classList.remove("disable");b.nextSibling.classList.remove("disable");b.classList.add("chakan");b.innerHTML="\u67e5\u770b";b.setAttribute("title","\u67e5\u770b");b.setAttribute("data-action","open_folder3")},800)}}function f(a){if(a&&(a.classList.remove("succ"),a=a.querySelector(".btn_left")))a.classList.remove("chakan"),a.classList.remove("downloading"),
a.classList.remove("disable"),a.nextSibling.classList.remove("disable"),a.classList.add("download"),a.innerHTML="\u4e0b\u8f7d",a.setAttribute("title","\u4e0b\u8f7d"),a.setAttribute("data-action","file_download")}function a(a){var b=a.parentNode.parentNode.parentNode;e.tasks.do_file_active(b);var c=e.client,d=e.model,b=a.parentNode.parentNode.parentNode;b.clickTime=new Date;a=d.getListDataMap()[b.id.substr(5)];console.debug(a);if(a)if(a.inDownload)setTimeout(function(){e.tasks.do_box_open()},10);else{var f=
a.filepath,h=a.filename_esc,i=a.filesize;a.fp=a.fp.replace("/myrecv","");e.cgi.checkFile(a.fp,a.t,function(a){a.ec===0&&a.audit===3?(c.alert("\u8be5\u6587\u4ef6\u56e0\u591a\u6b21\u88ab\u4e3e\u62a5\u4e3a\u8272\u60c5\u6587\u4ef6\uff0c\u5df2\u88ab\u5220\u9664"),a=d.removeListData(f),view.removeListRow(f,a)):a.ec===0&&c.addDownloadTask(f,h,i,true)})}else console.error("model\u7684datamap\u91cc\u6ca1\u6709\u8be5\u6570\u636e"+b.id);g("DOWNLOAD_BTN_CLICK")}var g=window.g_report,e;return function(){var e=
{};e.do_file_download=a;e.do_file_downloadfast=d;e.do_file_save=c;e.do_file_downloading=b;e.do_file_downloadsucc=h;e.do_file_downloadback=f;e.do_animation=i;return{init:k,tasks:e}}()});
define("modules/handler/file/permanent",["../../../util/toast2"],function(k){function d(b){a=b}function c(){var e=a.lastActiveRow,c=a.cgi,d=a.model,f=a.tasks.do_hide_menu;f();if(e)d=d.getListDataMap()[e.id.substr(5)],f=d.filepath,c.permanent(f,h(i,f,d.filesize,e));b("TMP2PERMANENT_CLICK")}function i(b,c,d,h){var i=a.model,o=a.client,m=a.capacity,q=h.ec;q===0?(k.show("\u8f6c\u5b58\u6210\u529f"),d.classList.remove("temp"),o="/102"+h.fp,i.updateListData({filepath:b,fp:o},"permanent"),m.holdSpace(c),
d.id="list_"+o):((c=g[q])||(c="\u672a\u77e5\u9519\u8bef"),q===25?o.confirm("\u7a7a\u95f4\u5df2\u6ee1\uff0c\u65e0\u6cd5\u8f6c\u5b58\u4e3a\u6c38\u4e45\u6587\u4ef6\n\u662f\u5426\u8981\u6269\u5927\u5bb9\u91cf?")&&window.open("http://qgroup.qq.com/share/upgrade.html"):(o.alert("\u8f6c\u5b58\u5931\u8d25 "+c||""),f({type:"error",msg:"\u8f6c\u5b58\u5931\u8d25fp["+b+"]ec["+q+"]",report:"ERR_CGI_PERMANENT"})))}var b=window.g_report,h=window.g_hitch,f=window.g_log,a,g={1:"\u6ca1\u6709\u767b\u9646\u6216\u767b\u9646\u6001\u5931\u6548",
2:"\u7cfb\u7edf\u5185\u90e8\u9519\u8bef",7:"\u6ca1\u6709\u7fa4\u6743\u9650",21:"\u4e0d\u662f\u4e0a\u4f20\u8005\u6216\u7fa4\u4e3b\u4e0d\u80fd\u8f6c\u6c38\u4e45",22:"\u4e0d\u80fd\u8de8\u7fa4\u8f6c\u6c38\u4e45\u6587\u4ef6",23:"\u767b\u5f55\u6001\u6821\u9a8c\u5931\u8d25",24:"\u7fa4\u6210\u5458\u5173\u7cfb\u6821\u9a8c\u5931\u8d25",25:"\u5bb9\u91cf\u6ee1\uff0c\u53ef\u4ee5\u5347\u7ea7",26:"\u5bb9\u91cf\u6ee1\uff0c\u4e0d\u80fd\u518d\u5347\u7ea7",27:"\u8981\u8f6c\u5b58\u7684\u6587\u4ef6\u4e0d\u5b58\u5728",
28:"\u6c38\u4e45\u7a7a\u95f4\u5bb9\u91cf\u8d85\u9650"};return function(){var a={};a.do_file_permanent=c;return{init:d,tasks:a}}()});
define("modules/handler/file/more",[],function(){function k(b){i=b}function d(b){var d=i.tasks.do_link_menu,f=document.getElementById("file_menu"),a=document.getElementById("file_list"),g=i.model,e;e=b.parentNode.parentNode.parentNode;var j=i.lastActiveRow!=e;j&&i.tasks.do_file_active(e);if(g=g.getListDataMap()[e.id.substr(5)]){if(j?d(b,true):d(b),f&&f.classList.contains("open")){b=b.getBoundingClientRect();a=a.getBoundingClientRect().right-b.right;d=f.offsetHeight;b=b.bottom+1-14;b+d>window.innerHeight&&
(b=b-d-25);f.style.right=a+"px";f.style.top=b+"px";g=[g.file_icon==="pic"&&g.can_preview,window.g_i_download_default_path,window.g_i_download_fast,true,g.can_rename,g.can_forever,true,true,g.can_delete];f=f.children;for(a=0;a<g.length;a++)g[a]?(f[a].classList.remove("disable"),f[a].setAttribute("tabIndex",1)):(f[a].classList.add("disable"),f[a].setAttribute("tabIndex",-1));c("ITEM_MORE_BTN_SHOWCLICK")}}else console.error("\u6ca1\u6709\u627e\u5230\u5bf9\u5e94\u7684\u6570\u636e"+e.id)}var c=window.g_report,
i;return function(){var b={};b.do_file_more=d;return{init:k,tasks:b}}()});
define("modules/handler/file/goUploader",[],function(){function k(b){i=b}function d(b){i.tasks.do_file_active(b.parentNode.parentNode.parentNode.parentNode);if(!i.isVisitor){var d=i.view;document.getElementById("file_list");var f=document.getElementById("sort_text"),a=document.querySelector("#sort>div[by='uploader']");if(!a||!a.classList.contains("selected")){var g=b.parentNode.querySelector(".selected"),b=b.getAttribute("upload_uin");d.renderList(null,{sortBy:"uploader",uploader:b,target:b});b=document.querySelector("#sort>div[by='uploader']");
(g=b.parentNode.querySelector(".selected"))&&g.classList.remove("selected");a.classList.add("selected");f.innerHTML=b.innerHTML;c("UPLOADER_LINK_CLICK")}}}var c=window.g_report,i;return function(){var b={};b.do_go_uploader=d;return{init:k,tasks:b}}()});
define("modules/handler/file/sort",[],function(){function k(b){i=b}function d(b){var d=i.view,f=i.tasks;if(b&&b.classList.contains("selected"))f.do_hide_menu();else{var a=document.getElementById("sort_text"),g=b.getAttribute("by"),e=b.parentNode.querySelector(".selected");e&&e!==b&&e.classList.remove("selected");b.classList.add("selected");a.innerHTML=b.innerHTML;d.renderList(null,{sortBy:g});f.do_hide_menu();c({time:"SORT_TIME_CLICK",type:"SORT_TYPE_CLICK",uploader:"SORT_AUTHOR_CLICK",download:"SORT_DOWNLOADTIME_CLICK",
size:"SORT_FILESIZE_CLICK"}[g])}}var c=window.g_report,i;return function(){var b={};b.do_sort=d;return{init:k,tasks:b}}()});
define("modules/handler/file/groupToggle",[],function(){function k(c){b=c}function d(c){var d=b.tasks,c=c.getAttribute("tid");if(c=document.getElementById(c)){var a=c.getAttribute("data-action"),d=d["do_"+a];typeof d==="function"&&d(c);d=c.parentNode;a=d.getBoundingClientRect();c=c.getBoundingClientRect();c=d.scrollTop+c.top-a.top;c<0&&(c=0);d.scrollTop=c}}function c(b){var c=document.getElementById("file_list"),a=b.getBoundingClientRect().top,d=c.getBoundingClientRect().top;a<d&&b.scrollIntoView(true);
var e=document.getElementById("group_top"),a=document.getElementById("t"+b.id),d=b.nextSibling;d.className.indexOf("collapse")>=0?(d.classList.remove("collapse"),b.classList.remove("collapse"),a.classList.remove("collapse")):(d.classList.add("collapse"),b.classList.add("collapse"),a.classList.add("collapse"));setTimeout(function(){c.scrollHeight<=c.clientHeight?e.classList.add("notfull"):e.classList.remove("notfull")},300);i("LIST_GROUPHEAD_CLICK")}var i=window.g_report,b;return function(){var b=
{};b.do_group_toggle=c;b.do_link_to=d;return{init:k,tasks:b}}()});
define("modules/handler/file/listScroll",[],function(){function k(a){h=a;a=document.getElementById("file_list");a.onmousewheel=g_hitch(c,a,{scrollTop:0,step:10,direct:1,interval:26});a.onscroll=b;a.onmousemove=d}function d(b){b=b.target;if(!a){for(var c=0;c<5;c++)if(b.id)break;else b=b.parentNode;if(b&&b.classList.contains("file")){var c=h.model.getListDataMap(),b=b.id.substr(5),d=c[b];d&&d.type_str=="\u56fe\u7247"&&!d.thumbUrl&&!d.query_thumb_retry&&(f&&clearTimeout(f),f=setTimeout(function(){d.query_thumb_retry=
true;h.tasks.do_query_thumb([d])},g))}}}function c(a,b,c){var d=c.wheelDelta;b.direct=d<0?1:-1;var d=a.scrollTop+parseInt(d*-100/120,10),f=a.scrollHeight-a.clientHeight;d>f&&(d=f);d<0&&(d=0);b.scrollTop=d;g_hitch(i,a,b)();c.preventDefault()}function i(a,b){var c=a.scrollTop,d=b.scrollTop,f=b.step,h=b.direct;c!=d?(d-=c,d>f&&(d=f*h),d<-1*f&&(d=f*h),a.scrollTop=c+d,b.timer=window.requestAnimationFrame?window.requestAnimationFrame(g_hitch(i,a,b)):setTimeout(g_hitch(i,a,b),b.interval)):b.handle&&(window.cancelAnimationFrame?
window.cancelAnimationFrame(b.timer):clearTimeout(b.timer))}function b(){var b=document.getElementById("file_list"),c=document.getElementById("group_top"),d=document.getElementById("box"),f=h.tasks.do_hide_menu;h.lastOpenMenu!==d&&f(true);for(var f=53,f=b.getBoundingClientRect().top,i=b.querySelectorAll(".group_title"),b=c.childNodes,d=i.length-1;d>=0;d--)if(i[d].getBoundingClientRect().top-f<=0){var k=i[d+1],i=0;k&&(f=k.getBoundingClientRect().top-f,f<26&&(i=f-26));if(b[d])b[d].style.top=i+"px";
(c=c.querySelector(".shown"))&&c!==b[d]&&c.classList.remove("shown");b[d].classList.add("shown");break}a&&clearTimeout(a);a=setTimeout(function(){a=null;h.tasks.do_fetch_thumb()},g)}var h,f,a,g=50;return function(){var a={};a.do_list_scroll=b;return{init:k,tasks:a}}()});
define("modules/handler/file/active",[],function(){function k(d){c=d}function d(d){c.tasks.do_hide_menu();c.lastActiveRow!=d&&c.lastActiveRow&&c.lastActiveRow.classList.remove("active");c.lastActiveRow=d;c.lastActiveRow.classList.add("active")}var c;return function(){var c={};c.do_file_active=d;return{init:k,tasks:c}}()});
define("modules/handler/file/jubao",["../../../util/toast2"],function(){function k(c){b=c}function d(){var c=b.lastActiveRow;if(c=b.model.getListDataMap()[c.id.substr(5)]){var a="http://jubao.qq.com/cn/jubao?appname=im&subapp=group_file&jubaotype=article";a+="&impeachuin="+b.info.uin;a+="&uin="+c.uploaduin;a+="&fid="+c.fp;a+="&fname="+c.filename_esc;console.log("url:"+a);b.state_inJubao=true;h.src=encodeURI(a);h.parentNode.classList.add("open");h.classList.add("open")}b.tasks.do_hide_menu(true);i("jubao_btn_click")}
function c(){console.log("jubao close");h.classList.remove("open");h.parentNode.classList.remove("open");b.state_inJubao=false}var i=window.g_report,b,h=document.getElementById("jubao");return function(){var b={};b.do_file_jubao=d;b.do_jubao_close=c;return{init:k,tasks:b}}()});
define("modules/handler/batch/b_open",[],function(){function k(a){f=a}function d(){f.tasks.do_hide_menu();c()}function c(){document.getElementById("app").classList.add("batchMode");f.state_inBatch=true;for(var a=document.querySelectorAll("#file_list .cbox:checked"),b=document.getElementById("btn_batch_delete"),e=[],c=0;c<a.length;c++){var d=a[c].parentNode.parentNode;(d=f.model.getListDataMap()[d.id.substr(5)])&&d.can_delete&&e.push(d)}a.length!==e.length?b.setAttribute("data-disabled",true):b.setAttribute("data-disabled",
false);i()}function i(){for(var b=document.querySelectorAll("#file_list .cbox:checked"),c="",d=f.model,h=0,i=0,c=d.getListDataMap(),k=0;k<b.length;k++){var q=c[b[k].parentNode.parentNode.id.substr(5)];q.can_delete&&i++;q&&q._localpath&&window.g_i_ifFileExist&&window.external.isFileExist(q._localpath)&&h++}c="\u5df2\u9009\u62e9<i>"+b.length+"</i>\u4e2a\u6587\u4ef6";!b.length||b.length===h?(d.getListData(),e.classList.add("disable")):e.classList.remove("disable");i?g.classList.remove("disable"):g.classList.add("disable");
a.innerHTML=c}function b(a){a.classList.contains("cbox")||(a=a.children[0]);a.checked?c():(a=document.querySelectorAll("#file_list .cbox:checked"))&&a.length?c():document.getElementById("app").classList.remove("batchMode");i();h("b_checkbox_click")}var h=window.g_report,f,a=document.getElementById("batch_total"),g=document.getElementById("btn_batch_delete"),e=document.getElementById("btn_batch_download");return function(){var a={};a.do_file_check=b;a.do_batch_open=c;a.do_start_batch=d;a.do_batch_update=
i;return{init:k,tasks:a}}()});define("modules/handler/batch/b_close",[],function(){function k(b){i=b}function d(b){document.getElementById("app").classList.remove("batchMode");i.tasks.do_unselect_all();i.state_inBatch=false;b&&c("b_return_click")}var c=window.g_report,i;return function(){var b={};b.do_batch_close=d;return{init:k,tasks:b}}()});
define("modules/handler/batch/b_download",["../../cleanTask","../../../util/toast2"],function(k,d){function c(a){g=a}function i(){for(var a=g.model.getBoxData().plist,c=0,d=0;d<a.length&&c<3;d++)/(downloadprogress|downloadgeturlend|downloadgeturl|downloadready)/g.test(a[d].status)&&c++;c=3-c;for(d=0;d<a.length&&c>0;d++)b(a[d]),c--}function b(a){if(/(wait)/g.test(a.status))a.status="downloadready",a.fp=a.fp.replace("/myrecv",""),g.cgi.checkFile(a.fp,a.t||a.busid,function(b){console.debug(b);b.ec===
0&&b.audit===3?(client.alert("\u8be5\u6587\u4ef6\u56e0\u591a\u6b21\u88ab\u4e3e\u62a5\u4e3a\u8272\u60c5\u6587\u4ef6\uff0c\u5df2\u88ab\u5220\u9664"),b=model.removeListData(a.filepath),view.removeListRow(a.filepath,b)):b.ec===0&&g.client.addDownloadTask(a.filepath,a.filename,a.filesize,true)})}function h(){a("b_download_click");var b=document.querySelectorAll("#file_list .cbox:checked"),c=[],h=g.model,k=h.getListDataMap(),l=0;if(b.length>999)return client.alert("\u5f53\u524d\u9009\u62e9\u4e0b\u8f7d\u7684\u6587\u4ef6\u8fc7\u591a\uff0c\u6700\u591a\u540c\u65f6\u4e0b\u8f7d999\u4e2a\u6587\u4ef6\uff0c\u8bf7\u51cf\u5c11\u6587\u4ef6\u4e2a\u6570\u540e\u91cd\u8bd5"),
false;var o={};h.getBoxData().plist.forEach(function(a){o[a.filepath]=true;a.status=="wait"&&l++});if(l>1E3)return client.alert("\u5f53\u524d\u6b63\u5728\u4e0b\u8f7d\u7684\u6587\u4ef6\u8fc7\u591a\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5"),false;for(var m=h=0,q=0;q<b.length;q++){var r=k[b[q].parentNode.parentNode.id.substr(5)];if(r)if(r._localpath&&window.g_i_ifFileExist&&window.external.isFileExist(r._localpath))h++;else if(o[r.filepath]==true)console.log("this file alredy downloading !"),m++;else{console.debug("download go file2Task !");
var s=f(r);o[r.filepath]=true;c.push(s);g.tasks.do_file_downloading(document.getElementById("list_"+s.filepath))}}g.tasks.do_batch_close();c.length>0&&c.length<b.length&&d.yes(""+(b.length-c.length)+"\u4e2a\u6587\u4ef6\u4e0d\u9700\u8981\u9700\u91cd\u590d\u4e0b\u8f7d");c.length===0?h>0&&d.yes("\u60a8\u8fd8\u6ca1\u6709\u9009\u62e9\u6587\u4ef6"):(b=g.model.updatePlist(c.reverse(),true),c=g.model.getBoxData(),g.view.updateBox(b,c,true),i(),g.tasks.do_animation())}function f(a){var b={},c;for(c in a)b[c]=
a[c];b.id=b.filepath;b.status="wait";b.type="download";b.filepath=a.filepath;b.filesize=a.filesize;b.filename=a.filename_esc;k.cleanItem(b);return b}var a=window.g_report,g;return function(){var a={};a.do_batch_download=h;a.do_batch_download_check=i;return{init:c,tasks:a}}()});
define("modules/handler/batch/b_delete",["../../../util/toast2"],function(){function k(a){e=a}function d(){f()}function c(){o=l=0;j.classList.remove("ready");j.classList.add("process");document.querySelectorAll("#file_list .cbox:checked");j.querySelector(".process").innerHTML="\u5220\u9664\u4efb\u52a1\u6267\u884c\u4e2d";i(p,0,function(){j.classList.remove("process");j.classList.add("done");var a=j.querySelector(".result"),b=document.querySelector("#batch_total i"),c=parseInt(b.innerText),d="";d+=
o?"\u5df2\u6210\u529f\u5220\u9664<span>"+l+"</span>\u4e2a\u6587\u4ef6,\u5931\u8d25<span>"+o+"</span>\u4e2a\u3002":"\u5df2\u6210\u529f\u5220\u9664<span>"+l+"</span>\u4e2a\u6587\u4ef6";p=null;a.innerHTML=d;c-l>0?b.innerText=c-l:e.tasks.do_batch_close()})}function i(a,c,d){var f=e.cgi;if(a&&a.length){var h=a[c];if(h){var g=h.filepath;f.deleteFile(g,g_hitch(b,a,c,d,g,h.remotetype,h.filesize))}}}function b(a,b,c,d,f,h,j){var k=e.model,n=e.view,p=e.capacity;console.warn("do delete result:",d);if(j&&j.ec===
void 0)j.ec=j.code;j.ec===0?(l++,j=k.removeListData(d),n.removeListRow(d,j),f===1&&p.releaseSpace(h),e.local.cgi.remove(d.substr(4)),g("DELETE_BTN_CLICK#SUCC")):(o++,g_log({type:"error",msg:"\u5220\u9664\u5931\u8d25fp["+d+"]ec["+j.ec+"]",report:"ERR_CGI_DELETE"}));a&&a.length&&b<a.length-1?i(a,b+1,c):c(true)}function h(){f()}function f(){var a=e.lastOpenMenu;a&&(a.classList.remove("open"),a.classList.remove("done"));e.lastOpenMenu=null}function a(){console.log("do_batch_delete");var a=document.querySelectorAll("#file_list .cbox:checked");
if(!(a&&a.length==0)){e.lastOpenMenu&&e.lastOpenMenu!=j&&e.lastOpenMenu.classList.remove("open");for(var b=[],c=0;c<a.length;c++){var d=a[c].parentNode.parentNode;(d=e.model.getListDataMap()[d.id.substr(5)])&&d.can_delete&&b.push(d)}a="\u60a8\u9009\u62e9\u4e86<span>"+a.length+"</span>\u4e2a\u6587\u4ef6,\u5176\u4e2d<span>"+b.length+"</span>\u4e2a\u6587\u4ef6\u53ef\u4ee5\u5220\u9664";b.length?(p=b,a+="<br>\u60a8\u786e\u5b9a\u8981\u5220\u9664\u8fd9<span>"+b.length+"</span>\u4e2a\u6587\u4ef6\u5417?",
b_delete_ok.classList.remove("disable")):b_delete_ok.classList.add("disable");n.innerHTML=a;e.lastOpenMenu=j;j.classList.remove("process");j.classList.remove("done");j.classList.add("ready");j.classList.add("open")}g("b_delete_click")}var g=window.g_report,e,j=document.getElementById("b_delete_panel"),n=j.querySelector(".hint"),p,l=0,o=0;return function(){var b={};b.do_batch_delete=a;b.do_b_delete_close=d;b.do_b_delete_ok=c;b.do_b_delete_cancel=h;return{init:k,tasks:b}}()});
define("modules/handler/batch/b_selectAll",[],function(){function k(c){b=c}function d(c){var d=document.querySelectorAll("#file_list .cbox"),c=c.checked;console.log("if checked:"+c);for(var a=0;a<d.length;a++)d[a].checked=c;b.tasks.do_batch_update();i("b_checAll_click")}function c(){for(var c=document.querySelectorAll(".cbox"),d=0;d<c.length;d++)c[d].checked=false;b.tasks.do_batch_update()}var i=window.g_report,b;return function(){var b={};b.do_select_all=d;b.do_unselect_all=c;return{init:k,tasks:b}}()});
define("modules/handler/body",["../../util/toast2"],function(k){function d(c){h=c;document.body.addEventListener("click",b);document.body.onselectstart=i}function c(){var b=h.cgi;k.hide();b.getList(h.tasks.do_get_cgidata)}function i(){return false}function b(b){var a=h.lastOpenMenu,c=h.lastOpenMenu2,e=h.tasks,d=h.client,i=h.info,k=e.do_box_close,l=document.getElementById("box"),o=b.target;if(o.id!="mask"){var m=o.getAttribute("data-action");if(!m)o=o.parentNode,m=o.getAttribute("data-action");if(!m){if(o&&
o.classList&&!o.classList.contains("file"))o=o.parentNode;o&&o.classList&&o.classList.contains("file")&&(m=o.getAttribute("data-action"))}if(m){var q=d.IsOnline();if(h.isVisitor&&!(m=="link_to"||m=="group_toggle"))return}if(m)if(o&&o.classList&&o.classList.contains("disable"))return;else e=e["do_"+m],typeof e==="function"&&e(o);if(m||!h.state_inRename&&!h.state_inJubao&&!h.state_inBatch)if(m&&(m.indexOf("rename")>=0||m=="file_active"||m=="download"||m=="file_download"||m=="file_downloadfast"||m==
"file_jubao"||m=="go_uploader"||m.indexOf("preview")>=0))k();else{m!=="box_toggle"&&m!=="file_upload"&&!l.contains(o)&&k();if(m!=="file_more")h.lastActiveRow&&h.lastActiveRow.classList.remove("active"),h.lastActiveRow=null;if(m!=="menu"&&m!=="link_menu"&&m!=="file_more"&&a&&!a.contains(o))a.classList.remove("open"),h.lastOpenMenu=null,c&&c.classList.remove("open"),h.lastOpenMenu2=null;a=o.name;m==="task_remove"&&(b.preventDefault(),b.stopPropagation());a==="enlarge"&&g_report("UPGRADE_LINK_CLICK");
a==="feedback"&&g_report("FEEDBACK_CLICK");if(a==="refresh")b=new Date,b.setTime(b.getTime()+6E4),document.cookie="refresh_"+i.uin+"_"+i.groupid+"=1; expires="+b.toGMTString()+"; path=/;"}}}var h;document.getElementById("rename_panel");return function(){var f={};f.do_body_click=b;f.do_page_reload=c;return{init:d,tasks:f}}()});
define("modules/handler/menu",[],function(){function k(c){b=c}function d(c){var d=b.lastActiveRow,a=b.lastOpenMenu,g=b.lastOpenMenu2;a&&a.classList.remove("open");g&&g.classList.remove("open");c!=true&&d&&d.classList.remove("active")}function c(c,d){var a=b.lastOpenMenu,g=b.lastOpenMenu2;document.getElementById("box");var e=c.getAttribute("menu"),j=document.getElementById(e);d!=true&&j.classList.contains("open")?(j.classList.remove("open"),c.classList.remove("open"),b.lastOpenMenu=null,b.lastOpenMenu2=
null):(a!==j&&a&&a.classList.remove("open"),g!==c&&g&&g.classList.remove("open"),j.classList.add("open"),c.classList.add("open"),b.lastOpenMenu=j,b.lastOpenMenu2=c,e==="sort"?i("SORT_ENTRY_SHOWCLICK"):e==="more"&&i("MORE_BTN_SHOWCLICK"))}var i=window.g_report,b;return function(){var b={};b.do_link_menu=c;b.do_hide_menu=d;return{init:k,tasks:b}}()});
define("modules/app.handler","./handler/cgi/queryThumb,./handler/cgi/getData,./handler/client/onMsg,./handler/client/newTask,./handler/client/taskProgress,./handler/client/taskComplete,./handler/client/taskAbort,./handler/client/taskPause,./handler/client/taskResume,./handler/box/init,./handler/box/pause,./handler/box/resume,./handler/box/continue,./handler/box/remove,./handler/box/boxToggle,./handler/box/clearHistory,./handler/box/openFolder,./handler/file/upload,./handler/file/delete,./handler/file/preview,./handler/file/rename,./handler/file/download,./handler/file/permanent,./handler/file/more,./handler/file/goUploader,./handler/file/sort,./handler/file/groupToggle,./handler/file/listScroll,./handler/file/active,./handler/file/jubao,./handler/batch/b_open,./handler/batch/b_close,./handler/batch/b_download,./handler/batch/b_delete,./handler/batch/b_selectAll,./handler/body,./handler/menu".split(","),function(){var k=
arguments,d={};d.dom_file_list=document.getElementById("file_list");d.tasks={};(function(c,d){for(var b=0;b<d.length;b++){var h=d[b],f;for(f in h.tasks)c[f]=h.tasks[f]}})(d.tasks,k);window.ctx=d;return{init:function(c,i,b,h,f,a,g){d.model=c;d.view=i;d.cgi=b;d.client=h;d.info=f;d.local=a;d.capacity=g;for(c=0;c<k.length;c++)k[c].init(d);window.g_time_cgi_start=new Date;c=d.tasks.do_get_cgidata;window.g_flag_cgi_enable&&b.getList(c);if(f.isVisitor)document.getElementById("app").classList.add("visitor");
else if(d.tasks.do_box_init(),window.g_flag_local_enable&&a.cgiData)(b=a.cgiData)&&b.ec===0&&d.tasks.do_get_data(b)},tasks:d.tasks}});
define("modules/app","./app.model,./app.view,./cgi,./client,./getInfo,./local,./capacity,./app.handler,../util/toast2".split(","),function(k,d,c,i,b,h,f,a,g){var e=window.g_report;return{run:function(){var j=b(),n=document.getElementById("app");j.uin?(c.init(j),h.init(j),k.init(j,h,i),a.init(k,d,c,i,j,h,f),e("TAB_FIRST_ENTER"),window.g_local?e("PROJ_VERSION_LOCAL"):e("PROJ_VERSION"),j.fromRefresh&&e("REFRESH_BTN_CLICK")):(n.style.display="none",g.no("\u672a\u767b\u5f55\u7528\u6237\u4e0d\u5141\u8bb8\u8bbf\u95ee",
{autoHide:0}))}}});
(function(k){typeof define==="function"?define("util/debug",[],k):k()})(function(){var k=false;document.addEventListener("keydown",function(d){if(d.keyCode===123&&d.ctrlKey&&!k){k=true;var c=void 0;document.getElementById("FirebugLite")||(c=(c=document.createElementNS&&document.documentElement.namespaceURI)?document.createElementNS(c,"script"):document.createElement("script"),c.setAttribute("id","FirebugLite"),c.setAttribute("src","http://pub.idqqimg.com/lib/firebug-lite/build/firebug-lite.js#startOpened"),c.setAttribute("FirebugLite",
"4"),(document.getElementsByTagName("head")[0]||document.getElementsByTagName("body")[0]).appendChild(c),c=new Image,c.setAttribute("src","http://pub.idqqimg.com/lib/firebug-lite/skin/xp/sprite.png"))}d.keyCode===116&&location.reload()},false)});require.config({baseUrl:"js"});require(["./modules/app","./util/debug"],function(k){window.TRecord.push("main","mainStart");k.run()});define("index",function(){});
