(function(h,g){typeof define==="function"&&define.amd?define([],g):h.Util=g(h.Str)})(this,function(){return function(){var h="",g="",i={debugOn:true,isd:function(a){setTimeout(function(){var b=new Image,c="http://isdspeed.qq.com/cgi-bin/r.cgi?flag1=7809&flag2=1&flag3=56&",d;for(d in a||{})c+=d+"="+a[d];b.src=c},2E3)},debug:function(a){if(this.debugOn){var b=document.createElement("p");b.innerHTML="debug: "+a;document.body.insertBefore(b,document.body.childNodes[0])}},hash:{get:function(a){a=top.location.hash.match(RegExp("(#|&)"+
a+"=([^&]*)(&|$)"));return!a?"":decodeURIComponent(a[2])},set:function(a){location.hash="#"+a}},encryptSkey:function(){for(var a=this.cookie.get("skey"),b=5381,c=0,d=a.length;c<d;++c)b+=(b<<5)+a.charAt(c).charCodeAt();return b&2147483647},node:{html:function(a,b){if(b)a.innerHTML=b;else return a.innerHTML}},cookie:{get:function(a){a=document.cookie.match(RegExp("(^| )"+a+"=([^;]*)(;|$)"));return!a?"":decodeURIComponent(a[2])},uin:function(){var a=this.get("uin");return!a?null:parseInt(a.substring(1,
a.length),10)}},http:{ajax:function(a,b,c,d,f){var e=new XMLHttpRequest;e.open(d,a,true);e.onreadystatechange=function(){e.readyState==4&&(e.status>=200&&e.status<300||e.status===304||e.status===1223||e.status===0?typeof f=="undefined"&&e.responseText?c(eval("("+e.responseText+")")):c(e.responseText):c({ec:e.status}),e=null)};e.send(b)},post:function(a,b,c,d){var f="",e;for(e in b)f+="&"+e+"="+b[e];return this.ajax(a,f,c,"POST",d)},get:function(a,b,c,d){var f=[],e;for(e in b)f.push(e+"="+b[e]);a.indexOf("?")==
-1&&(a+="?");a+=f.join("&");return this.ajax(a,null,c,"GET",d)}},init:function(){h=this.hash.get("groupuin");g=this.hash.get("role");return this},getAvatars:function(a,b){var a=true,c=this.hash.get("groupuin");info=null;head_type=2;level=-1;ret=[];key="";r=Math.random();try{info=JSON.parse(top.external.GetGroupBasicInfo(c+""))}catch(d){info={}}info==null&&(info={},Badjs("window.external.GetGroupBasicInfo("+c+")==null, from:Util.js",window.location,0,356050,2));head_type=info.head_type;head_type==
2?(ret=["http://p.qlogo.cn/gh/"+c+"/"+c+"/100","http://p.qlogo.cn/gh/"+c+"/"+c+"/40"],this.addRandom(ret,a),b&&b(ret)):(ret=["http://p.qlogo.cn/gh/"+c+"/"+c+"/100","http://p.qlogo.cn/gh/"+c+"/"+c+"/40"],this.addRandom(ret,a),this.getFace(function(a){a&&ret.unshift(a);b&&b(ret)}));return ret},addRandom:function(a,b){var c=Math.random(),d=false,d=localStorage.getItem("group_avatar_random");b?(localStorage.setItem("group_avatar_random",c),d=true):d?(c=d,d=true):d=false;if(d)for(d=0;d<a.length;d++)a[d]=
a[d]+"?r="+c;return a},tryAvatar:function(a,b){var c=this,d=null,f=Array.prototype.slice.call(arguments,1);if(f.length){if(!a.nodeType)d=a.onload||null,a=a.img;var e={};if(typeof f[0]==="string")e.url=f[0];var g=new Image,h=new Date-0;g.onerror=function(){this.onerror=null;e.onerror&&e.onerror();c.tryAvatar.apply(c,[a].concat(f.slice(1)));LOG({type:"error",msg:"\u7fa4\u5934\u50cf\u52a0\u8f7d\u5931\u8d25\uff01 ",url:location.href,mid:372032})};g.onload=function(){var b=new Date-0-h;b>1E3&&LOG({type:"error",
msg:"\u7fa4\u5934\u50cf\u52a0\u8f7d\u8d85\u8fc71s\uff01t= "+b,url:location.href,mid:372033});c.isd({17:b});this.onload=null;e.onload&&e.onload();a.src=e.url;d&&d(this.width,this.height)};g.src=e.url}},updateAvatar:function(a,b){var c=this;setTimeout(function(){c.getAvatars(b,function(b){b.unshift(a);c.tryAvatar.apply(c,b)})},50)},wrapClientBasicInfoToCGIFormate:function(a){a.gName=Str.encodeHtml(a.name||"");a.gMemNum=a.cur_mem_num||"";a.gMaxMem=a.mem_max||"";var b=(a["class"]||"").split("-")[0]||
"",b=b.split(".").join("");a.classInfo=Str.encodeHtml(b||"");return a},isNotGroupMember:function(){return g!=1&&g!=2&&g!=3},getPerfTimeStamp:function(){var a={};try{a=JSON.parse(external.CallHummerApi("Default.GetPerfTimeStamp"))}catch(b){a={}}return a},createScript:function(a){var b=document.createElement("script"),c="",d=function(){},f=function(){};typeof a!=="string"?(c=a.src,d=a.onload||d,f=a.onerror||f):c=a;b.async=false;b.src=c;b.onload=d;b.onerror=f;document.head.appendChild(b)},createScripts:function(a){var b=
this;a.forEach(function(a){b.createScript(a)})},seq:9999,hasUpdatedFaceCallback:false,updateFaceCallback:function(a){var b=this;if(!this.hasUpdatedFaceCallback){var c=window.callback;window.callback=function(d){c&&c(d);d.seq==b.seq&&a&&a(d)};this.hasUpdatedFaceCallback=true}},getFace:function(a){var b=new Date-0,c=this;this.updateFaceCallback(function(d){c.isd({18:new Date-0-b});var f="";if(d.ec==0)f=d.grp[h].u;a&&a(f)});this.createScript("http://face.imweb.qq.com/cgi-bin/face?app=group_info&redir=0&seq="+
this.seq+"&grp=100|"+h)},getShutTime:function(a){a-=30;return a<3540?Math.ceil(a/60)+"\u5206\u949f":a<82800?Math.ceil(a/3600)+"\u5c0f\u65f6":Math.ceil(a/86400)+"\u5929"},adjust:function(a,b,c){var d=a.width,f=a.height;d/f>b/c?(a.height=c,a.width=d*(c/f),a.style.marginLeft=-(a.width-b)/2+"px"):(a.width=b,a.height=f*(b/d),a.style.marginTop=-(a.height-c)/2+"px")}};window.CommonUtil=i.init();return i}()});
